### ISSUE TITLE
Memory leak in Magick.Net-Q16-x86 7.8.0 ? 

### ISSUE THREAD

**Issue by toan69nguyen** [dlemstra/Magick.NET#340] opened 2018-10-18 06:59 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Hi @dlemstra ,

I am using the Magick.Net.Net-Q16-x86 v 7.8.0 in a small console application. 
It is being used to convert  svg text to bmp image. 
I am using RED ANT to do the memory profiling and seeing that the memory occupied by Magick.Net is growing a little every time . Here is the how to reproduce it 
### Steps to Reproduce

I have a simple class MgTester with the following fucntion : 

```
public void PrintBagTag( string svgString )
        {         
                {
                    MagickReadSettings setting = new MagickReadSettings();
                    setting.Format = MagickFormat.Svg;
                    setting.Density = new Density(300, 300);

                    var svgBytes = Encoding.ASCII.GetBytes(svgString);

                    using (MemoryStream ms = new MemoryStream())
                    {
                        using (MagickImage iim = new MagickImage(svgBytes, setting))
                        {
                            iim.Format = MagickFormat.Bmp;

                            iim.Write(ms);
                            _bagtag = Image.FromStream(ms);
                        }

                    }
                    
                    if (_bagtag != null)
                        PrintDocument.Print();
                    
                    if (_bagtag != null)
                        _bagtag.Dispose();
                    _bagtag = null;
                }
            }

And Here is the main program : 

        static void Main(string[] args)
        {
            var mgTester = new MgTester();

            Console.WriteLine("Press any key to start the test! ");
            Console.ReadKey();

            for (int j = 0; j < 3; j++)
            {
                for (int i = 0; i < 100; i++)
                {
                    string BagTagSvg;
                    BagTagSvg = File.ReadAllText(@"TestBagTag.svg");

                    Task.Factory.StartNew(() =>
                    {

                        mgTester.PrintBagTag(BagTagSvg);
                    });

                    Thread.Sleep(4000);
                }


                Console.WriteLine("Lot : " + j.ToString() );
                Console.ReadKey();
            }

            Console.WriteLine("Press any key to exit! ");
            Console.ReadKey();
            

        }
    }
```

This application is printing 3 lots of a bmp image , which is a conversion from a SVG text . The SVG text is read from a SVG file . Each lot it repeats the  conversion and print for 100 times. 
After the first lot the RED ANT profiler is telling me that Magick.Net is occupying  1.426 Mb 
After the second lot  Magick.Net is occupying  2.275 Mb 
After the third lot  Magick.Net is occupying  3.048 Mb 

Can you please have a look ? 
If you want I can send you the whole project .  
### System Configuration

- Magick.NET version:7.8.0
- Environment (Operating system, version and so on): Windows 10 Pro 64 bit x64- based proccessor . RAM 32 Gb 

- Additional information:

**Comment by dlemstra** [comment] 2018-10-18 10:32
Can you reproduce your issue when you remove:

```C#
if (_bagtag != null)
    PrintDocument.Print();
                    
if (_bagtag != null)
    _bagtag.Dispose();
_bagtag = null;
```

**Comment by toan69nguyen** [comment] 2018-10-18 12:52
Hi @dlemstra,
Yes , I can reproduce the issue with out the printing. Here are the result after removing the code as per your recommendation: 

After the first lot the RED ANT profiler is telling me that Magick.Net-Q16-x86.Native is occupying 1.427 Mb
After the second lot Magick.Net is occupying 2.272 Mb
After the third lot Magick.Net is occupying 3.045 Mb

Yes I can shere the SVG image . It is in the attachment . 
[TestBagTag.zip](https://github.com/dlemstra/Magick.NET/files/2491941/TestBagTag.zip)

Please let me know if you have any issue with the attached file. 

REGARDS

**Comment by dlemstra** [comment] 2018-10-20 12:36
It looks like there is an issue inside the librsvg library somewhere. But I don't have the expertise to figure out why it fails inside that library. You might want to switch to using inkscape instead.

**Comment by yang-xiaodong** [comment] 2018-11-25 03:31
`Magick.NET-Q16-AnyCPU - 7.9.0.1`  still have a memory leak, In Docker in our production environment, memory takes 2 days and starts from 150M and becomes 1G.

**Comment by dlemstra** [comment] 2018-11-25 08:45
@yang-xiaodong Can you create a reproducible example and open a new issue instead? This issues is about reading SVG files under Windows.

**Comment by dlemstra** [comment] 2018-11-27 21:00
Closing this issue because I cannot fix it.

**Closed by dlemstra** 2018-11-27 21:00 UTC
Labels: bug
