### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by MattiaCamponesco** [dlemstra/Magick.NET#787] opened 2020-11-18 13:40 UTC
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi everyone,
I'm becoming crazy trying to understand causes of a bug while converting a TIF file into a PNG file.
A short description of my particular case: I have written a little application for my company to convert images coming from PS into a little PNG preview that are showed in a management page in our Extranet Application dedicated to our designers.

In particular, this morning, for a specific TIF image, application raised the exception in the object.
`System.AccessViolationException: Attempted to read or write protected memory`

This is the StackTrace:
```
in ImageMagick.MagickImage.NativeMethods.X64.MagickImage_WriteFile(IntPtr Instance, IntPtr settings, IntPtr& exception)
in ImageMagick.MagickImage.NativeMagickImage.WriteFile(IMagickSettings`1 settings)
in TosiLabGraficheSync.Managers.ImageManager.GeneraAnteprimaFileImmagine(TosGraficheReparti reparto, FileInfo fileInfo, ImageDto grafica)
in D:\GIT\TosiLabGraficheSync\TosiLabGraficheSync\TosiLabGraficheSync\Managers\ImageManager.cs:riga 83
```

And here is the code snippet that goes on error:
```
[HandleProcessCorruptedStateExceptions]
        private ImageDto GeneraAnteprimaFileImmagine(TosGraficheReparti reparto, FileInfo fileInfo, ImageDto grafica)
        {
            try
            {
                Process.OperationStopwatch = new Stopwatch();
                Process.OperationStopwatch.Start();

                using (MagickImage image = new MagickImage(fileInfo))
                {
                    var fiAnteprima = ApplicationSettings.REPO_AnteprimeRepartoGrafica_PathFile(reparto, fileInfo);
                    SetImageInfoData(grafica, image);

                    var destinationPath = fiAnteprima.FullName;
                    if (File.Exists(destinationPath)) File.Delete(destinationPath);

                    int previewWidth = ApplicationSettings.GRAF_Preview_ImageWidthPx;
                    int previewHeight = image.Height * previewWidth / image.Width;

                    image.Resize(previewWidth, previewHeight);
                    image.Format = PreviewImageMagickFormat;
                    image.Write(destinationPath);

                    ImageOptimizer optimizer = new ImageOptimizer();
                    optimizer.IgnoreUnsupportedFormats = true;
                    optimizer.Compress(destinationPath);

                    grafica.AnteprimaGenerata = GeneratePreview(image, fiAnteprima.FullName);
                }

                Process.OperationStopwatch.Stop();
                LogManager.Info(Process, "Generata anteprima file immagine", fileInfo.FullName);
            }
            catch (Exception ex)
            {
                LogManager.Error(Process, ex, fileInfo.FullName);
            }
            return grafica;
        }
```

The Exception is raised during image.Write method call.

### System Configuration

- Magick.NET version: Magick.NET.Core 5.2.0 + Magick.NET-Q8-AnyCPU 7.22.2
- Environment (Operating system, version and so on): Windows 10 Enterprise - 10.0.17763
- Additional information:

**Comment by dlemstra** [comment] 2020-11-18 14:00
Can you create a small code sample that reproduces this issue? You now have calls to various methods that have unknown behavior. And can you share the input image that has this issue with that sample?

**Comment by MattiaCamponesco** [comment] 2020-11-18 14:22
I have reproduce it, only using one method and calling standard library methods as follow:
```
[HandleProcessCorruptedStateExceptions]
        public void Test()
        {
            try
            {
                var imageSource = new FileInfo(@"C:\Temp\source.tif");
                var imageDestination = new FileInfo(@"C:\Temp\detination.png");

                using (MagickImage image = new MagickImage(imageSource))
                {
                    int previewWidth = 300;
                    int previewHeight = image.Height * previewWidth / image.Width;

                    image.Resize(previewWidth, previewHeight);
                    image.Format = MagickFormat.Png;
                    image.Write(imageDestination.FullName);

                    ImageOptimizer optimizer = new ImageOptimizer();
                    optimizer.IgnoreUnsupportedFormats = true;
                    optimizer.Compress(imageDestination.FullName);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(string.Empty);
                Console.WriteLine(ex.StackTrace);
            }
        }
```

What I have noticed while debugging the small code sample is that the exception is alway raised in the method below the instruction Image.Write indipendently on which is.

This is the exception raised
![2020-11-18_15h21_10](https://user-images.githubusercontent.com/74658001/99541909-b2c2e780-29b1-11eb-93ea-0f54ce044f4b.png)

**Comment by dlemstra** [comment] 2020-11-18 14:53
Without your input image I cannot reproduce this issue.

**Comment by MattiaCamponesco** [comment] 2020-11-18 15:00
This is the [link](https://filesharing.systemceramics.com/AreaDiScambio/DownloadHandlerAreaDiScambio.aspx?Token=a0710d31-0798-44b1-8507-2a376a05cc89) to download it...

**Comment by dlemstra** [comment] 2020-11-20 12:11
Thanks for your file and I am able to reproduce your issue. Will need to figure out how to solve it though.

**Comment by dlemstra** [comment] 2020-11-24 17:00
The issue has been found and fixed. This will be resolved in the next release of Magick.NET

**Closed** 2020-11-24 19:22 UTC
Labels: bug
