### ISSUE TITLE
Cannot convert from AVIF to BMP

### ISSUE THREAD

**Issue by SebastianStehle** [dlemstra/Magick.NET#1189] opened 2022-05-23 19:49 UTC
### Magick.NET version

11.12

### Environment (Operating system, version and so on)

Windows, .NET 6

### Description

I have an asset library that supports different formats and stores. I have tests for conversion for all formats, and when I run the test for AVIF -> BMP I have the following behaviors:

1. The bmp file is way too big. 6MB instead of 1.3MB or so, for a 600x600 image.
2. When I load the bmp I get the following error: `{"length and filesize do not match `' @ error/bmp.c/ReadBMPImage/847"}`

### Steps to Reproduce

Checkout: git@github.com:Squidex/assets.git

Run the following test:

![image](https://user-images.githubusercontent.com/1236435/169894888-7fb04b8f-8176-4211-b23f-fc3b2bf8bf7b.png)

**Comment by dlemstra** [comment] 2022-05-23 20:07
Could you reduce this to a small code sample that I can use to reproduce your issue? Otherwise I would need to debug your code.

**Comment by SebastianStehle** [comment] 2022-05-23 20:39
Here it is: https://github.com/SebastianStehle/magicktest/tree/main/MagickTest

**Comment by dlemstra** [comment] 2022-05-23 21:57
The problem here is how the image is written. Because you are using the `Async` method the image is first written to a `byte` array in memory and then saved to the file to make it possible to do the IO part asynchronous. When you don't use the async method separate files would be created. This is a bug that has to be fixed in Magick.NET but that won't solve your issue because looking at your code it seems that you are using a stream instead of a file. And when you are using a stream each "file"/frame will be written to that output stream sequentially. This is by design but I don't know if anyone even uses that.

In your situation I would advise you to use `MagickFormatInfo.Create(MagickFormat)` and then use the `IsMultiFrame` property to determine what you want to do. You should probably use a `MagickImage` when `IsMultiFrame` returns `false` instead of a `MagickImageCollection`.

**Comment by SebastianStehle** [comment] 2022-05-23 22:21
But it only happens with bmp and in my sample I do not use streams. All other conversions work.

**Comment by SebastianStehle** [comment] 2022-05-23 23:21
Okay, my code was probably wrong. I have changed the saving to this: https://github.com/Squidex/assets/blob/master/Squidex.Assets.ImageMagick/ImageMagickThumbnailGenerator.cs#L125

And this works.

It seems that when I load the avif as collection it has 5 images. No idea, why. And therefore all five images are saved to the bmp stream or file.

**Comment by dlemstra** [comment] 2022-06-19 17:21
When you load an image with the `MagickImageCollection` you will get all the layers/frames of the image.

**Closed by dlemstra** 2022-06-19 17:21 UTC

**Comment by SebastianStehle** [comment] 2022-06-19 18:12
Yes. I know. But I created the avif by converting from png manually. So I don't see how it can have more than one 1 layer.
