### ISSUE TITLE
Creating a new image, then adding to a collection causes a MemoryException

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#436] opened 2019-05-14 19:59 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When creating a new image from the ImageMagik API, and then adding it to a collection repeatedly (cloning) it crashes. However, I created the image myself in photoshop, used a file instead of a image in memory, I do not get a System.AccessViolationException

### Steps to Reproduce

```cs
var random = new Random();

using (var avatar = new MagickImage(await HttpClient.GetByteArrayAsync(user.AvatarURL(256))))
//using (var baseImage = new MagickImage(MagickColors.Transparent, 256, 256 + 38))

// if I uncomment the above, instead of using the below (which is a tranparent image, 256x294) I get a System.AccessViolationException. Seems to be from a native dispose method on the collection

using(var baseImage = new MagickImage("./Assets/Images/Triggered/triggered_base.png"))
using (var collection = new MagickImageCollection())
{
		
    avatar.Resize(320, 320);
		
    for (var i = 0; i < 40; i++)
    {
	    var clone = baseImage.Clone();
	    clone.Composite(avatar, random.Next(-32, 32), random.Next(-32, 32)); // I have tried to clone the avatar also, same deal
	    collection.Add(clone);
    }

    var bytes = collection.ToByteArray();
    await ReplyAsync(new File("triggered.gif", bytes));
}
```
### System Configuration
.NET Core 2.2 latest.

- Magick.NET version: Latest Q8 x64 (non OpenMP version)
- Environment (Operating system, version and so on): Windows 10 latest non preview, x64 AMD FX-8350 CPU

**Comment by dlemstra** [comment] 2019-05-14 20:48
Could you state the version? A new version has been published yesterday so I just want to make sure that we are talking about the same version. And would it be possible to create a reproducible example with image urls? Feel free to send me an email with those urls if you want to keep those private.

**Comment by Tylertron1998** [comment] 2019-05-17 17:22
Hi! Sorry for the long reply - can confirm the bug is still on the latest version - I was a version behind when reporting this bug.

I seem to have narrowed it down, either: 
A) creating a base image from the API, instead of using a file, will cause the AVE.

OR

B) not giving collection.ToByteArray() a MagickFormat will also crash it.

I have a repo you can clone and reproduce the bug here: https://github.com/Tylertron1998/ImageMagickBug

**Comment by dlemstra** [comment] 2019-05-17 17:27
Thanks for the repo, this will make it so much easier to reproduce the issue. Will try to take a look at it this weekend.

**Comment by dlemstra** [comment] 2019-05-19 07:46
Thanks for the detailed information it really made it much easier to fix this bug. The problem is the mapping of the native WriteStream method of MagickImageCollection. The C# code thought it would return an instance but the native method is void. Your code raised an exception because you are trying to write the image in the `xc` format and that is not supported. And because an exception was raised the instance that was returned should be freed. But because the method did not really return an instance the C# code just a 'random' memory location and that will cause an access violation. I just pushed a patch to fix this and this will be resolved in the next version of Magick.NET that I will try to publish next week.

**Comment by Tylertron1998** [comment] 2019-05-20 00:18
Awesome, I'm glad to help! (:

**Closed** 2019-05-21 22:03 UTC
Labels: bug
