### ISSUE TITLE
Grayscale and Quantize on PSD generates corrupted file

### ISSUE THREAD

**Issue by vlad-vi** [dlemstra/Magick.NET#474] opened 2019-06-26 15:43 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This code creates invalid file:
```
var fi2 = new FileInfo(@"....\190132LCZ.psd");
IMagickImage image2 = new MagickImage(fi2);

image2.Resize(new MagickGeometry(-1, 200));
// following 2 lines causes to created invalid image
image2.Grayscale(PixelIntensityMethod.Average);
image2.Quantize(new QuantizeSettings
{
	Colors = 256,
	ColorSpace = ImageMagick.ColorSpace.Gray
});

image2.Depth = 8;
image2.ColorSpace = ColorSpace.Gray;
image2.Format = MagickFormat.Psd;
image2.AutoOrient();

image2.Write(@".......\22222.psd");
```
Such exception is thrown, when I try to call GetColorProfile on that 22222.psd file:

> ImageMagick.MagickCorruptImageErrorException: 'insufficient image data in file `........\22222.psd' @ error/psd.c/ReadPSDImage/2413'

When I use image magick cli it shows different error though:
magick: unable to decompress image `......\22222_GrayScale.psd' @ error/psd.c/ReadPSDChannel/1442.

Original file:
https://drive.google.com/file/d/1LaKrxcZVmGAMhiMoAwo6kjzCpja9L31S/view

- Magick.NET version: 7.14.0.1

**Comment by dlemstra** [comment] 2019-06-27 15:23
Thanks for reporting this. This seems to be an issue inside ImageMagick and I just pushed a patch to fix this. This will be resolved in the next version of Magick.NET.

**Comment by vlad-vi** [comment] 2019-07-01 09:32
@dlemstra Hi! thank you for the update. But after I updated to 7.14.0.2 I still have the same issue.

**Comment by dlemstra** [comment] 2019-07-01 10:28
That's odd. Will take another look at this tonight.

**Comment by dlemstra** [comment] 2019-07-02 21:12
I can reproduce your issue but and it looks to be related to the compression of the image. Will get back to you when I have more info.

**Closed** 2019-07-16 18:59 UTC
Labels: bug, upstream

**Comment by mdemettre** [comment] 2021-11-22 09:57
I'm having this exact issue again on v8.4.0.
The `Quantize` function is causing invalid image headers.

**Comment by dlemstra** [comment] 2021-11-22 21:09
We don't have access to Photoshop so we cannot test your issue @mdemettre and it looks like you have a different problem here? Can you please start a new discussion or issue that explains the problem in more detail.
