### ISSUE TITLE
ImageMagick.MagickCorruptImageErrorException: 'insufficient image data in file @ error/tiff.c/ReadTIFFImage/1774'

### ISSUE THREAD

**Issue by CFekkes** [dlemstra/Magick.NET#915] opened 2021-04-27 17:50 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

An error is thrown when creating a MagickImage from a compressed TIF of which the width is multiple times bigger than the height. 

Exception Unhandled: 

> ImageMagick.MagickCorruptImageErrorException: 'insufficient image data in file 'E:\Test.tif' @ error/tiff.c/ReadTIFFImage/1774'

### Steps to Reproduce

The following code fails:
```
static void Main()
{
        string outputFilepath = @"E:\Test.tif";
        int width = 145;
        int height = 16;
  
        IMagickImage<float> image = new MagickImage(new MagickColor(256, 0, 0), width, height);
        var tiffWriteDefines = new TiffWriteDefines { Alpha = TiffAlpha.Unspecified };
  
        image.Settings.Compression = CompressionMethod.Zip;
        image.Write(outputFilepath, tiffWriteDefines);
  
        MagickImage result = new MagickImage(outputFilepath); // this will crash
}
```

### Notes
- The error does not occur when the image is not compressed.
- The error does not occur when the height is multiple times bigger than the width.
- The error does not occur with width = 144 (or lower) and height = 16, but will occur when the width is higher than 144.

### System Configuration

- Magick.NET-Q16-HDRI-x64 version 7.23.4
- Windows 10 x64
- Visual Studio 2019 v16.8.6

**Comment by dlemstra** [comment] 2021-04-28 05:52
I can reproduce your issue and will need to investigate why this is happening. It looks like the zip compression is causing this. This can also be an issue in the tiff library that we are using.

p.s. If you are `IMagickImage<float>` it looks like you are using the HDRI version instead?

**Comment by CFekkes** [comment] 2021-04-28 07:30
> p.s. If you are IMagickImage\<float\> it looks like you are using the HDRI version instead?

You are right my bad, I've changed it.

**Comment by CFekkes** [comment] 2021-04-28 07:30
> I can reproduce your issue and will need to investigate why this is happening. It looks like the zip compression is causing this. This can also be an issue in the tiff library that we are using.
> 
> p.s. If you are `IMagickImage<float>` it looks like you are using the HDRI version instead?

**Comment by dlemstra** [comment] 2021-05-05 16:03
You were getting this message due to some security restrictions that we added to the TIFF coder. But the check that we added was not correct, there will be a fix for this in the next release of Magick.NET.

**Closed** 2021-05-10 14:08 UTC
