### ISSUE TITLE
EXIF data not available

### ISSUE THREAD

**Issue by 48design** [dlemstra/Magick.NET#132] opened 2017-12-10 11:52 UTC
Hi,

I tried to use the EXIF data from my images but I do always get "null". With another library (MetadataExtractor, which is a bit oversized for me...) I can read the information so it is available.

The code used is the one found inside the documentation:
```
// Read image from file
using (MagickImage image = new MagickImage("FujiFilmFinePixS1Pro.jpg"))
{
  // Retrieve the exif information
  ExifProfile profile = image.GetExifProfile();

  // Check if image contains an exif profile
  if (profile == null)
    Console.WriteLine("Image does not contain exif information.");
  else
  {
    // Write all values to the console
    foreach (ExifValue value in profile.Values)
    {
      Console.WriteLine("{0}({1}): {2}", value.Tag, value.DataType, value.ToString());
    }
  }
}
```
profile is always null. Test image: https://www.48design.de/downloads/raw_images/raw_image.7z

**Comment by dlemstra** [comment] 2017-12-10 15:07
Do you also have a smaller test image that contains EXIF information that I could use in a unit test if this turns out to be a bug? Max 1mb? If you can point me to a location where I can download such a file that would also help a lot.

**Comment by 48design** [comment] 2017-12-10 15:14
You can use this one:
![img_6777](https://user-images.githubusercontent.com/1440241/33806218-0fa8bb00-ddc5-11e7-8ba1-ac5c30401e63.jpg)
It should be reproducable with every image containing EXIF data I think.

**Comment by dlemstra** [comment] 2017-12-10 15:34
`image.GetExifProfile()` does not return null with that test image (33806218-0fa8bb00-ddc5-11e7-8ba1-ac5c30401e63.jpg)?

**Comment by 48design** [comment] 2017-12-10 17:18
Oh, you are absolutely right! I've tested this with CR2, TIF and PNG but not with JPG... I tried it with the jpg and it really works! I didn't use it because of possible problems with artifacts. Shouldn't it work with other image formats? The library I mentioned above (MetadataExtractor) does read the information from the image file formats above.

**Comment by dlemstra** [comment] 2017-12-10 18:37
It should work with PNG and TIF as long as they have an exif profile. I did some research and it turns out we don't read the EXIF data when we decode the CR2 files. Will need to check if we can add support for that. I will get back to this issue when I know more.

**Comment by 48design** [comment] 2017-12-10 18:44
That sounds great! It doesn't explain the PNG and TIF problem but those are good news anyway!
Thank you very much!!

**Comment by dlemstra** [comment] 2017-12-10 19:00
Could you add a PNG and a TIFF file that show that problem to this issue? Make sure you first check if they really have an exif profile.

**Comment by 48design** [comment] 2017-12-10 19:18
I've uploaded a TIF with EXIF information:
[IMG_6777_small.zip](https://github.com/dlemstra/Magick.NET/files/1545964/IMG_6777_small.zip)

I checked the PNGs again and it seems the EXIF information was indeed lost when converting from RAW, so there doesn't seem to be an issue. My research tells me that PNGs normally don't have EXIF information inside to this is not a problem on MagickNET's side. :)

**Comment by dlemstra** [comment] 2017-12-10 21:18
For the tiff format you will need to iterate through the `image.AttributeNames` and find the attributes thats start with `"exif:"` but you cannot get them as an ExifValue. And it looks like we only set `dng:` attributes for the RAW files at the moment. Already did some investigating into how we could parse the exif information but that won't be easy. Will need to do some more research when I have some free time to check this.

**Comment by 48design** [comment] 2017-12-11 12:51
Thank you very much for your efforts!

**Comment by flemingm** [comment] 2018-01-21 03:09
First off thank you for your work!

Sample PNG File with EXIF data.
[http://imagemontage.com/preview/EXIFExample.png](http://imagemontage.com/preview/EXIFExample.png)

CR2 files can be parse like TIFF file to access The EXIF data.
Detail at: [http://lclevy.free.fr/cr2/](http://lclevy.free.fr/cr2/)

**Comment by dlemstra** [comment] 2018-05-19 07:03
@jackbond This issue is about adding support for reading exif information from a RAW file. ImageMagick reads and writes exif information inside PNG files so that should work. Could you open a new issue instead if you have problems with reading and writing exif information inside a PNG file? Please also include a sample so I can easily reproduce it.

**Comment by spinningcat** [comment] 2020-04-07 08:30
Yesterday I tried to read exif informations. I couldnt manage to do it in magick.net however when i try with exiftools i saw EXIF informations. I guess this issue opened years ago.

**Comment by TomQv** [comment] 2021-11-08 23:34
Same for me, just tried code from first post with some random photos which contains exif and GetExifProfile() always returns null. ImageMagick-7.1.0-Q8

**Comment by dlemstra** [comment] 2021-11-22 19:28
Adding support for reading EXIF information in raw files doesn't look like an easy task. There seems to be support for reading individual tags but that would mean we will need to "reconstruct" the exif profile.

**Comment by NVFedorov** [comment] 2021-12-17 08:53
Trying to remove EXIF data:
```
      using (MagickImage image = new MagickImage(s))
      {
          var profile = image.GetExifProfile();
          if (profile != null)
          {
              image.RemoveProfile(profile.Name);
          }

          MemoryStream sOut = new MemoryStream();
          image.Write(sOut);

          return sOut;
      }
```

```profile``` is null for the sample image provided above (https://user-images.githubusercontent.com/1440241/33806218-0fa8bb00-ddc5-11e7-8ba1-ac5c30401e63.jpg). However there is EXIF data there (verify here: http://exif-viewer.com/)

**Comment by kmgallahan** [comment] 2023-08-05 01:07
@dlemstra Is not being able to read EXIF data from raw files a Magick.NET or ImageMagick limitation?

Can ImageMagick read individual EXIF values given their names?

**Comment by dlemstra** [comment] 2023-08-05 12:52
Please read my comments from earlier and I will now close this issue now because it seems to be hijacked for various things.

**Closed by dlemstra** 2023-08-05 12:52 UTC
Labels: enhancement, help wanted
