### ISSUE TITLE
[7.0.0.104+] SVG to JPG/PNG Produces a Blank White Image

### ISSUE THREAD

**Issue by OphiCA** [dlemstra/Magick.NET#30] opened 2016-12-21 23:45 UTC
Using any version since (and including) 7.0.0.104 produces a blank white image when trying to convert an SVG source to PNG or JPEG (or presumably any other rasterized image). The latest version I tried is 7.0.3.902 and it's still producing a blank image. To make sure it's not an issue with ImageMagick, I downloaded and installed version 7.0.4.0 and ran the following command:

```
magick.exe convert "C:\Test.svg" "C:\Test.png"
```

It correctly produced the expected PNG image. This leaves me to believe that the issue is with Magick.NET and how it's delegating to ImageMagick. The following code is what I've used with 7.0.0.103, but it doesn't working with 7.0.0.104+ and I don't know of any other way to make the conversion:

```
string value = "...";
byte[] bytes;

using (var memoryStream = new MemoryStream()) {
	using (var streamWriter = new StreamWriter(memoryStream)) {
		streamWriter.Write(value);
	}

	using (var magickImage = new MagickImage(memoryStream, new MagickReadSettings {
		Format = MagickFormat.Svg
	})) {
		bytes = magickImage.ToByteArray(MagickFormat.Png24);
	}
}

File.WriteAllBytes(@"C:\Test.png", bytes);
```

I'd appreciate any suggestions if I'm doing something wrong, or if it really is an issue with Magick.NET if it could be fixed. I've been using 7.0.0.103 and ignoring all updates solely because of this issue. I'm attaching a sample SVG for testing. This is being used inside of an ASP.NET MVC 5 web app on .NET 4.6.2. Thanks in advance!

[Test.svg.txt](https://github.com/dlemstra/Magick.NET/files/667640/Test.svg.txt)

**Comment by dlemstra** [comment] 2016-12-22 20:11
I can reproduce your issue and it is definitely a Magick.NET issue. It should do the same thing as the magick.exe command but I am also getting a different result. I will need to investigate why this is happening.

p.s. Your could should not have worked in the first place and it will throw an Argument exception in the next version of Magick.NET. The `StreamWriter` closes the stream and you are passing in a non-readable stream. But due to an optimization that directly access the bytes of the buffer it does not fail.

**Comment by OphiCA** [comment] 2016-12-27 02:51
Thanks for getting back to me. When you said the `StreamWriter` was closing the stream, I decided to see if I can rework the code. I ended up with this:
```
byte[] pngBytes;
var svgBytes = Encoding.UTF8.GetBytes(value);

using (var magickImage = new MagickImage(svgBytes, new MagickReadSettings {
	Format = MagickFormat.Svg
})) {
	pngBytes = magickImage.ToByteArray(MagickFormat.Png24);
}
```
Then I updated to the latest version and it's working fine. Months ago when I made the other version I had spent so long getting it to work that I just settled for what it was. Thanks for the help!

**Comment by dlemstra** [comment] 2016-12-27 06:20
Your issue will be resolved with Magick.NET 7.0.4.100 as you have noticed. I made the change so your original code would still work. It will probably be more efficient than getting the bytes yourself.

**Closed by dlemstra** 2016-12-27 06:20 UTC
Labels: bug
