### ISSUE TITLE
MagickCacheErrorException: no pixels defined in cache on TGA Files 

### ISSUE THREAD

**Issue by Stromberg90** [dlemstra/Magick.NET#382] opened 2019-02-03 16:16 UTC
In my image viewer program, I noticed on the latest version 7.10.2 it fails when loading tga files.
`MagickCacheErrorException: no pixels defined in cache`
So I went back through earlier versions to see at which point it worked, it works on 7.9.2 but not after.

Related code:
```csharp
ImageSettings.ImageCollection = new MagickImageCollection {Path};
```

**Comment by dlemstra** [comment] 2019-02-03 20:14
This is caused by patch in issue #368. This will be resolved in the next release.

**Closed** 2019-02-10 17:37 UTC
Labels: bug
