### ISSUE TITLE
255,255,255 getting converted to 0,255,0 with 7.3.0

### ISSUE THREAD

**Issue by scohen2002** [dlemstra/Magick.NET#158] opened 2018-02-02 19:18 UTC
Hi, i recently upgraded via NuGet to 7.3.0. I often upgrade to the latest version every time i put out a new release.

Without changing any code something very weird an un-expected happens. I downgraded back to 7.2.1 and confirmed the problem went away. If you look at the following code fragment i've attached step0.jpg and step1.jpg, using 7.3.0 it makes all of the "blow highlights" of the following image turn from pure white to pure green. Using 7.2.1 they stay pure white.
![step0](https://user-images.githubusercontent.com/6952817/35750730-f82ebc52-0823-11e8-946c-eb09189d77af.jpg)
![step1](https://user-images.githubusercontent.com/6952817/35750731-f83c2b08-0823-11e8-825f-02b1913e56ab.jpg)

                using (MagickImage image = new MagickImage(incomingStream))
                {
                    image.Write(@"c:\step0.jpg");
                    ColorProfile imageICC = image.GetColorProfile();
                    if (imageICC != null && imageICC != ColorProfile.AdobeRGB1998)
                        image.TransformColorSpace(imageICC, ColorProfile.AdobeRGB1998);
                    image.Write(@"c:\step1.jpg");

**Comment by dlemstra** [comment] 2018-02-02 20:16
I can reproduce your issue and it looks like a bug in the Q16 version of Magick.NET.  It stays white with the Q8 build. I will need to investigate this some more but it looks like it works on the command line. I will probably need to use the latest version of ImageMagick to resolve this issue. Will get back to you when I know more.

**Comment by dlemstra** [comment] 2018-02-04 17:32
I figured out what caused this. In the ImageMagick project we recently enabled [HDRI](https://www.imagemagick.org/script/high-dynamic-range.php) when transforming color spaces. This means that we can end up with values that are higher than zero. Then when the value gets multiplied `1,001 * 65535` the value will become `65600` and that value will be cast to an `ushort` and become `64`. I just pushed a patch for this to the ImageMagick repository and this will be resolved in the next version of Magick.NET.

**Comment by scohen2002** [comment] 2018-02-04 18:13
Thanks much for figuring it out and fixing it. I'll watch out for the next version.

**Comment by dlemstra** [comment] 2018-02-04 21:19
@scohen2002 Can you give it another try with the new release that I just published? Feel free to close this issue if this solves your problem.

**Comment by scohen2002** [comment] 2018-02-06 15:58
I downloaded 7.4.0 and the problem does appear fixed now. This was an interesting one, our photo processing software is tested by a fully automated testing suite, but we missed this one, we never imagined needing a test to verify that color values were altered in ways we didn't expect!

Thanks again for the very quick turn around time.

**Closed** 2018-02-06 15:58 UTC
Labels: bug
