### ISSUE TITLE
Writing an animated .gif as animated .webp fails after upgrade to Macick.NET vers 12.3.0

### ISSUE THREAD

**Issue by davidei1955** [dlemstra/Magick.NET#1357] opened 2023-03-06 02:31 UTC
### Magick.NET version

Magick.NET-Q8-AnyCPU 12.3.0

### Environment (Operating system, version and so on)

Windows 11 x64, .NET 7.0, MSTest, Visual Studio 2022

### Description

I recently upgraded from Magick.NET-Q8-AnyCPU from version 8.6.1 to 12.3.0.  The following unit test was working, but now throws an exception:
`        [TestMethod]
        public void TestConvertAnimatedGif() {
            using (var animatedGif = new MagickImageCollection(@"D:\Email\Inbox\TestWebPImages\animated.gif")) {
                animatedGif.Write(@"D:\Email\Inbox\TestWebPImages\animated-webp.webp", MagickFormat.WebP);
            }
        }
`
animated.gif is attached here:
![animated](https://user-images.githubusercontent.com/79710713/223005766-0f359a33-0966-4728-a72d-dd1c0fb4542c.gif)

The exception message is:
`    Test method UnitTests.ImageMagickTests.TestConvertAnimatedGif threw exception: 
ImageMagick.MagickCoderErrorException: ERROR adding frame: Invalid frame dimensions. `D:\Email\Inbox\TestWebPImages\animated-webp.webp' @ error/webp.c/WriteAnimatedWEBPImage/965

  Stack Trace: 
MagickExceptionHelper.Check(IntPtr exception) line 18
NativeHelper.CheckException(IntPtr exception) line 27
NativeMagickImageCollection.WriteFile(IMagickImage image, IMagickSettings`1 settings) line 907
MagickImageCollection.Write(String fileName) line 1670
MagickImageCollection.Write(String fileName, MagickFormat format) line 1702
ImageMagickTests.TestConvertAnimatedGif() line 28
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
`

### Steps to Reproduce

Add an MSTest unit test project to a Visual Studio 2022 .NET 7.0 solution.
Add the test method listed above.
Run it.

**Comment by dlemstra** [comment] 2023-03-06 16:32
Duplicate of #1349.

**Closed by dlemstra** 2023-03-06 16:32 UTC

**Comment by davidei1955** [comment] 2023-03-06 17:29
My google-fu must be off. Adding image.Coalesce() fixed the test. Thanks!
