### ISSUE TITLE
MagickCollection.Write hangs when writing large PDF files

### ISSUE THREAD

**Issue by MadAboutImport** [dlemstra/Magick.NET#918] opened 2021-05-05 12:27 UTC
Using Magick.NET-Q8-AnyCPU 7.23.4 ; Which in experience is a fantastic library, thank you.

The issue I have found is specific to writing large (lots of pages) PDFs; and is particularly acute with large numbers of mono (bilevel tifs using group 4 compression) images.

When using to write out a large collection to a multipage PDF file I find that the method hangs.

So the code;

using (MagickImageCollection convertedImages = new MagickImageCollection())
{
          // Add the files to the destination images using the full path to a multiframe tif
          convertedImages.AddRange(sourcefile.GetFullPathToFile());

          // Write the pdf (hangs at this method)
          convertedImages.Write(FullPathToTempFile,  settings.PDFA ? MagickFormat.Pdfa : MagickFormat.Pdf);

}

The description;

The problem occurs on Q16 / Q8 and whether the image collection is populated from .AddRange or new MagickImageCollection(fullpathtofile)

The problem is far more acute on mono (bilevel tifs using group 4 compression) than color.

As an aside it is noticeable that saving a single frame of an originally group 4 compressed tif to PDF takes 3000ms.

Adding the following;

                                if (image.Settings.Compression == CompressionMethod.Group4)
                                {
                                    image.Settings.Compression = CompressionMethod.Zip;
                                }

... Reduces the same operation to 600ms.  This increases speed but large collections still cannot be written.

On my configuration anything over 400 pages causes the issue but it is noticeable that performance starts to drop off at a lower number of pages.

Whilst the method is hung (left for several hours) temp files continue to be written to temp (i.e. C:\Users\Administrator\AppData\Local\Temp)

To reproduce you need @ 400+ frames in the source (bilevel tifs using group 4 compression)

Using Windows 10 on a VMWare with 16Gb memory and 2 cores allocated.

Any thoughts on solutions or alternative approaches to writing PDFs with lots of pages appreciated.

**Comment by MadAboutImport** [comment] 2021-05-06 12:22
Note that adding the following enables a situation where the conversion of CCITT group 4 compressed works.

            ResourceLimits.LimitMemory(new Percentage(30));
            ResourceLimits.Thread = 1;
            // 10Gb disk limit
            ResourceLimits.Disk = 10737418240;

Note quite sure why this makes a difference as the machine was well specced and was not running out of resources.

With these resource settings the following reduces conversion time by a factor of 5 but increases the size of the resultant PDF

if (image.Settings.Compression == CompressionMethod.Group4)
{
    image.Settings.Compression = CompressionMethod.Zip;
}

**Comment by dlemstra** [comment] 2021-05-11 22:08
Using `Group4` compression will need to change the type of the image to `BiLevel` (monochrome). It is possible that changing the pixels to only black and white reduces the size of the image. It is also possible that `Group4` compression is more efficient for your specific images compared to `Zip` compression.

The slow down is most likely caused by ImageMagick switching to disk (the temp files) to store the images pixels instead of in memory. Instead of using the `AnyCPU` version you probably want to switch to `x64`. It is possible that your `AnyCPU` process is running in 32-bit mode and then you will run out of memory a lot faster.

**Comment by MadAboutImport** [comment] 2021-05-12 10:12
Thanks for the update.  The problem does appear to be specific to the Group 4 compression format and not the bit depth.

I get the following performance for the small 3 page bi level input image in converting to PDF.  The input image uses CCITT Group 4 compression originally.  The timing is the duration in seconds of the convertedImages.Write call and the size is of the resultant PDF.

Group4 / Fax - 5.4294239 Seconds - 284Kb

Zip - .89 seconds - 296Kb

JBIG2 - .391 seconds - 1368Kb

JPEG - .5054664 seconds - 2564 Kb

Recompression using zip is considerable quicker as you can see.

I was surprise to see JBIG2 increasing the size of the file but perhaps is writes with 8bit color because it can?  I did fource bilevel (image.Settings.ColorType = ColorType.Bilevel;) but this makes not difference.

The original input image is 279Kb.  

[SmallMultiPageTif.zip](https://github.com/dlemstra/Magick.NET/files/6465407/SmallMultiPageTif.zip)

**Comment by dlemstra** [comment] 2021-07-04 09:30
We have made various performance improvements in ImageMagick and with your tiff image the write method is now a lot faster. Can you confirm this @MadAboutImport so we can close this issue?

**Comment by MadAboutImport** [comment] 2021-07-06 12:46
On version 7.2.4 (Q8) saving with compression type fax (CCITT group IV) takes 4.8 seconds.

 

The same image on the same machine with 8.0.0 takes .7 seconds so the performance uplift is significant between the two versions.

 

Magick indeed!

**Closed** 2021-07-06 12:52 UTC
