### ISSUE TITLE
DivideByZeroException

### ISSUE THREAD

**Issue by GieltjE** [dlemstra/Magick.NET#793] opened 2020-11-23 10:13 UTC
### Prerequisites
- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of Magick.NET
- [X] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
On some (bad) machines resizing an image causes an DivideByZeroException, on these machines the hit rate is 100%, on other machines it never happens. The image being loaded in the example below is just a generic 512x512px png.

Code:
```
MagickImage magickImage = new MagickImage();
magickImage.Read(file);
image.Resize(new MagickGeometry(15, 15));
```
Trace:
```
at ImageMagick.MagickImage.NativeMagickImage.Resize(String geometry): 
at ImageMagick.MagickImage.NativeMethods.X64.MagickImage_Resize(IntPtr Instance, IntPtr geometry, IntPtr& exception): 
System.DivideByZeroException: Attempt to divide by zero.
```
It is fixed by:
```
OpenCL.IsEnabled = false;
```

### Steps to Reproduce
This one is hard to reproduce, it only happens on some (presumably) bad GPU (drivers).

### System Configuration
- Magick.NET version: Magick.NET-Q16-OpenMP-x64 v7.22.2.1
- Environment: Win 10 Business (Pro) 20H2, fully up to date including VC++ 14.28.29515.1
- Additional information:

**Comment by dlemstra** [comment] 2020-11-23 11:01
Do you have any additional information about the GPU/driver that is being used? Could also be a bug in the OpenCL driver when it is asked a question that it doesn't understand. Does this also happen when you use an image of a different size? Might be related to how the work load is spread across the GPU. With a debug build of Magick.Native you might be able to debug the problem yourself and find the exact line of code or call to GPU where this is happening.

**Comment by GieltjE** [comment] 2020-11-23 13:19
PC: NUC7i5DNB
Windows build: 19042.630
CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 virtual) (X64)
GPU: HD620 iGPU
GPU Drivers: 27.20.100.8682 (5/9/2020)

Using a different size image also gives the same crash, I have full access to the machine and to all code. So if you want me to run some test version that should be no problem.

**Comment by dlemstra** [comment] 2020-11-24 10:27
You should be able to run Visual Studio on that machine with a debug version of this library: https://github.com/dlemstra/Magick.Native and make your application/unit test crash. This should then give you a more detailed stack trace and hopefully include the location where this is happening.

**Comment by GieltjE** [comment] 2020-12-16 10:16
Sorry building it is way to much hassle, do not have the time for it. Will just disable HW acceleration for now on that machine.

**Comment by dlemstra** [comment] 2020-12-16 10:52
I am located in the Netherlands so maybe we can work something out in the future.

**Comment by M4nju** [comment] 2020-12-17 12:58
@dlemstra I just got the same error now on my development Pc. Thought i implemented a bug but no.  Our Software includes Magick.Net Version 7.16.1 and i tried resolving it updating to Version 7.22.1. This didnt help. 

BUT: We recently created nuget packages from our Framework and somehow the Magick.Net.Core nuget package was missing. I added it and now everything works fine :)

(Before i found the missing nuget package the OpenCl workarround also worked for me). Maybe this is also the solution for @GieltjE  ?

**Comment by M4nju** [comment] 2020-12-17 13:00
If you need something from me to investegate this issue feel free to let me know :)

**Comment by M4nju** [comment] 2020-12-17 13:01
I am on an Intel Core i5-8600 CPU with Intel UHD Graphics 630. Driver-Version 27.20.100.8682  from the 05.09.2020

**Comment by GieltjE** [comment] 2020-12-17 13:16
@M4nju if you could help debug that would be awesome, currently the only PC i have available is with a client and is nearly always in use.

**Comment by M4nju** [comment] 2020-12-17 13:17
Oh somehow didnt saw this comment. I fill fix some other things today and than i will look into it

**Comment by M4nju** [comment] 2020-12-18 13:14
Well i am sorry to say that i cannot reproduce the error anymore. I implemented the Magick.Native Nuget package in a Test-Console applikation but there i couldn´t reproduce it. So i went back to the applikation wher i had the error and tried to reproduce it with the same files i used yesterday. But again everthing worked. 

The only thing that may have fixed it are these driver updates (U can see the first installation Failed "Fehler bei der Installation"). Maybe this will help you?

![image](https://user-images.githubusercontent.com/38355359/102618504-3865be80-413b-11eb-9e51-2b2793727bfd.png)

**Comment by M4nju** [comment] 2020-12-18 13:15
And also this WIndows Update happened, but it was just a anti-maleware update:
![image](https://user-images.githubusercontent.com/38355359/102618678-8084e100-413b-11eb-86b8-9214f4dc65ce.png)

**Comment by dlemstra** [comment] 2021-01-17 09:19
I suspect that an update to the display driver fixed this for you @M4nju.

**Comment by dlemstra** [comment] 2021-04-18 12:41
Future version of Magick.NET will have OpenCL disabled by default.

**Closed by dlemstra** 2021-04-18 12:41 UTC
