### ISSUE TITLE
'TIFFWriteDirectoryTagData' @ error/tiff.c/TIFFErrors/565`

### ISSUE THREAD

**Issue by adimkov** [dlemstra/Magick.NET#26] opened 2016-11-28 13:40 UTC
Hi, 

I'm using magick net library to convert image from jpg/png image into tif. Besides conversion I need apply some transformation for image (Trim, SetColorProfile, Resize, etc.). 
For most of images it works just well, but for some of them it throws error like: 
`IO error writing tag data. 'TIFFWriteDirectoryTagData' @ error/tiff.c/TIFFErrors/565. `

This error not happens if during conversion skipped SetColorProfile step. Before similar error was for Trim, but we updated library from version "Magick.NET.Core-Q8 7.0.2.400", to "Magick.NET.Core-Q8 7.0.3.300", and it fixed problem, but now it happens for another operations. Stack trace does not told me reason of error: 
`"at ImageMagick.MagickImage.NativeMagickImage.WriteBlob(MagickSettings settings, UIntPtr& length)\r\n 
at ImageMagick.MagickImage.Write(Stream stream)\r\n 
at ImageMagick.MagickImage.ToByteArray()\r\n " `
NOTE: Console tool of ImageMagick works for problematin image. 

I prepared sample to reproduce the problem. https://github.com/inteno/ImageMagickTifError

I also created issue at Codeplex, because i'm not sure what is primary source.
https://magick.codeplex.com/workitem/1417

**Comment by dlemstra** [comment] 2016-11-28 13:47
I respond to both places so I will close the one on CodePlex. And thanks for providing me with a great sample that I can use to reproduce it. Will take a look at it this week.

**Comment by dlemstra** [comment] 2016-11-28 21:23
The problem is the call to ToByteArray that causes a seek inside the tiff writer. Due to a bug the buffer cannot be resized and an exception is thrown. I just pushed a fix to the git repository of ImageMagick. Your issue will be resolved in the next version of Magick.NET.

**Comment by adimkov** [comment] 2016-11-29 11:48
Thank you

**Comment by dlemstra** [comment] 2016-11-29 16:54
Is this an urgent matter? I can push out a new release later this week if that will help you.

**Comment by adimkov** [comment] 2016-11-29 16:59
I will check it with Write method, instead of ToByteArray. In any case we can wait for next planned release.
Thank you 👍

**Comment by MatthiasJost** [comment] 2016-12-05 09:44
@dlemstra I am working with @adimkov . We have seen your fix in ImageMagick about the "Blob". We tried a workaround with MemoryStream instead of the toByteArray method. We could not workaround it. A new release would help us a lot to close the case. We have a large base of images we can test with. As soon as the new release comes out, we would test again. Thank you!

**Comment by dlemstra** [comment] 2016-12-05 23:01
The new release has been published. Please let me know if this solved your issue so we can close this issue.

**Comment by dlemstra** [comment] 2016-12-10 18:28
@adimkov or @MatthiasJost can you let me know when I can close this issue?

**Comment by MatthiasJost** [comment] 2016-12-12 09:38
@dlemstra Thanks a lot for providing the fix. Anton told me recently it worked in his test. We are going to create now a release of our application. In case we would encounter any further issue (after we tested with more images) we would let you know on this thread/issue or in a new one.

In general we are very happy with your library and thankful that you could help us so fast. 

In case you are interested more in detail of our application, we would be happy to present you what prototype we built based upon your .NET wrapper for ImageMagick.  I sent you a contact form on codeplex with all our contact details.

**Comment by MatthiasJost** [comment] 2016-12-13 15:31
@dlemstra Thank you Dirk for fixing it. Anton (@adimkov) reported to me a few minutes ago, that he tested successfully with a larger amount of images. He converted 6764 source images to 20292 output images. Considering the larger amount of test files we have been used: You may want to go ahead and close the issue, because we did not encounter any issues.

**Closed** 2016-12-13 16:53 UTC
Labels: bug
