### ISSUE TITLE
question about transfer svg to png

### ISSUE THREAD

**Issue by crazyboy12** [dlemstra/Magick.NET#2] opened 2015-12-10 07:41 UTC
hi,it seems that I had met a bug when I transfer svg to png , when I transfer a svg to png,it seems that
i can not transfer  japenese word with writing-modle:tb rightly in a svg ,
this is the svg file

**Comment by crazyboy12** [comment] 2015-12-10 08:00
```
<?xml version="1.0"?>
<svg width="1118.740157480315" height="793.7007874015749" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
  <g>
    <title>Layer 1</title>
    <rect id="rect-1025" fill="none" stroke-width="0" stroke="#000000" height="424" width="107" y="167.05797" x="438.95654" />
    <text writing-mode="tb" transform="translate(-44.92753601074219,-2.8985507488250732) scale(1,0.9906542301177979) " id="text_1025" font-size="107" x="537.38407" y="171.55989" text-anchor="start" font-family="NIS_R4NC" fill="#000000" xml:space="preserve">お品書き</text>
  </g>
</svg> 
```

**Comment by dlemstra** [comment] 2015-12-10 11:53
What is your operating system and ImageMagick version. And which SVG delegate are you using (output from `convert -list format | grep -i svg`)

**Comment by crazyboy12** [comment] 2015-12-11 03:07
my operating system is win7 32bit ,and the magick.net verison is Magick.NET 7.0.0.0021 the svg is mostly like this
```
<svg width="1118.740157480315" height="793.7007874015749" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
  <g>
    <title>Layer 1</title>
    <rect id="rect-1025" fill="none" stroke-width="0" stroke="#000000" height="424" width="107" y="167.05797" x="438.95654" />
    <text writing-mode="tb" transform="translate(-44.92753601074219,-2.8985507488250732) scale(1,0.9906542301177979) " id="text_1025" font-size="107" x="537.38407" y="171.55989" text-anchor="start" font-family="NIS_R4NC" fill="#000000" xml:space="preserve">お品書き</text>
  </g>
</svg>
```

**Comment by dlemstra** [comment] 2015-12-11 06:08
Oh my bad I did not realize this was posted in the Magick.NET section. I thought this was an ImageMagick issue.

Did you save your file in an UTF8 encoding?

**Comment by crazyboy12** [comment] 2015-12-11 06:46
yes i try this file in utf8 and unicode ,but it dosen't work

**Comment by dlemstra** [comment] 2015-12-11 07:59
I have the feeling I misunderstood your initial question. Are you seeing the text but is it written in the wrong direction?

**Comment by crazyboy12** [comment] 2015-12-11 08:59
un,No the svg has been convert to png but 
```
<text writing-mode="tb" transform="translate(-44.92753601074219,-2.8985507488250732) scale(1,0.9906542301177979) " id="text_1025" font-size="107" x="537.38407" y="171.55989" text-anchor="start" font-family="NIS_R4NC" fill="#000000" xml:space="preserve">お品書き</text>
```
can not be converted rightly ,the word "お品書き" was converted as four pane ，not this word "お品書き"  in Vertical .

**Comment by dlemstra** [comment] 2015-12-11 11:00
It might be possible that librsvg does not support this. This is the library that is used to read SVG images. I will investigate this and get back to you when I know more.

**Comment by dlemstra** [comment] 2015-12-12 00:11
Do you have the font NIS_R4NC installed on your system? If you don't have the font installed the svg library will just draw a square for each of your characters.

**Comment by crazyboy12** [comment] 2015-12-13 14:12
but when I convert this svg text to png without "writing-td" ,the magick.net work very good

**Comment by dlemstra** [comment] 2015-12-13 17:04
I thought it was a font loading issue on my system but when I replace it with a default Japanese font I still get the error. The issue seems to be that librsvg wants a 'rotated-left' version of the font but I don't have that on my system.

I found the following in the TODO for librsvg: https://github.com/ImageMagick/librsvg/blob/master/TODO
> "International" issues - bi-directional, top->bottom, etc.

And the code for librsvg contains this comment:
```c
} else if (g_str_equal (name, "writing-mode")) {
   /* TODO: these aren't quite right... */
```
You might be able to 'make this more important' if you report a bug here: https://bugzilla.gnome.org/enter_bug.cgi?product=librsvg

**Comment by crazyboy12** [comment] 2015-12-17 03:19
I am so sorry , but I may find another bug ,when I use this dll to convert a svg with linearGradient  to png,I find it also can not convert this svg rightly this svg is mostly like this
```
<svg width="793.700787401575" height="1118.74015748032" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <g>
  <title>Layer 1</title>
  <rect id="svg_15" height="324.47736" width="438.25513" y="325.49348" x="97.65691" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="5" stroke="#000000" fill="url(#svg_12)"/>
 </g>
 <defs>
  <linearGradient id="svg_12">
   <stop offset="0" stop-color="#c42121"/>
   <stop offset="1" stop-color="#3bdede"/>
  </linearGradient>
 </defs>
</svg>
```

**Comment by dlemstra** [comment] 2015-12-17 12:18
I can reproduce your issue with the current version of Magick.NET. This has been fixed in the latest development build. You will get a correct image in the next version of Magick.NET (7.0.0.0023)

**Comment by crazyboy12** [comment] 2015-12-25 00:45
Is it about the "writing-mode:td"?

**Comment by dlemstra** [comment] 2015-12-25 08:30
No that is about the second issue that you reported here. As I told you earlier (https://github.com/dlemstra/Magick.NET/issues/2#issuecomment-164277568) the "writing-mode:td" bug should be reported to librsvg.

**Comment by crazyboy12** [comment] 2015-12-28 01:23
I had reported to librsvg

**Comment by dlemstra** [comment] 2015-12-28 07:41
It might be a while before you get an answer to your bug report (https://bugzilla.gnome.org/show_bug.cgi?id=759431). I will close this Magick.NET issue for now.

**Closed by dlemstra** 2015-12-28 07:41 UTC
