### ISSUE TITLE
MagickImage.CropToTiles method causes extreme memory usage

### ISSUE THREAD

**Issue by nigtwisj** [dlemstra/Magick.NET#893] opened 2021-04-02 14:26 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I take a specific gif into an imagemagickcollection from a byte array and then loop through every frame in that collection where i resize it to a specific size and then call CropToTiles on that frame. After the 14th frame it gets stuck in the CropToTiles method and keeps eating up all the memory on the machine.

### Steps to Reproduce
Attempt to read this gif into the code below https://media1.tenor.com/images/a41df8ee310e15547bf5431cb16cc257/tenor.gif?itemid=20133682

```
//Read the gif from byte array
            using var collection = new MagickImageCollection(bytes, MagickFormat.Gif);
            //Create a new tileCollection to hold all the tiles.
            List<MagickImageCollection> tileCollection = new List<MagickImageCollection>();
            //Width is 5 and height is 5
            var tileSize = width * height;

            //Create a new size using the gifsize const which is 64
            var size = new MagickGeometry(GIFSIZE * width, GIFSIZE * height)
            {
                IgnoreAspectRatio = true
            };
            //Add ImageCollections to the tileCollection list to hold each
            //specific frames specific tile
            for (int i = 0; i < tileSize; i++)
            {
                tileCollection.Add(new MagickImageCollection());
            }
            //Loop over each frame
            foreach (var frame in collection)
            {
                //Resize it
                frame.Resize(size);
                //Crop each frame into 64x64 images.
                var g = frame.CropToTiles(GIFSIZE, GIFSIZE);
                var tiles = g.ToArray();

                for (int i = 0; i < tileSize; i++)
                {
                    tileCollection[i].Add(tiles[i]);
                }
            }
```
Watch as it gets stuck on the 14th iteration and eats all the memory.
https://cdn.discordapp.com/attachments/478542345990569985/827533536651247616/unknown.png <- Image of snapshots and memory
https://cdn.discordapp.com/attachments/478542345990569985/827533789713661992/unknown.png <- Image of latest snapshot

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU version 7.23.3
- Environment (Operating system, version and so on): Windows 10 pro but same issue on Ubuntu 20.04.2
- Additional information:

**Comment by dlemstra** [comment] 2021-04-17 22:12
Did you try to keep it running? When ImageMagick runs out of memory it will try to store it's memory on disk instead and that is much slower.

**Comment by nigtwisj** [comment] 2021-05-04 13:33
Yes, i tried keeping it running on my main machine and it just never finished. On my linux machine it sat for 4 hours and never finished and then disconnected all my discord bots on the machine.

**Comment by dlemstra** [comment] 2021-05-11 14:04
It looks like you are missing a `using` here: `var g = frame.CropToTiles(GIFSIZE, GIFSIZE);` This should be `using var g`. And I also don't see you "cleaning up" (disposing) the `tileCollection`

**Comment by nigtwisj** [comment] 2021-05-24 12:34
When trying to do a using statement on that line i get "'IEnumerable<IMagickImage<ushort>>': type used in a using statement must be implicitly convertible to 'System.IDisposable'.". Am I missing something obvious here and doing something wrong?

**Comment by dlemstra** [comment] 2021-05-29 09:12
Sorry I read your code incorrectly. The point that I was trying to make is that you will need to `.Dispose()` all the images after you are done with them.

**Comment by nigtwisj** [comment] 2021-06-15 18:59
I have now figured out what the issue is with this and you might be interested in knowing about this issue. The issue isn't in the way I dispose things in the code. The issue lies in the gifs themselves. The gifs that caused this issue to happen had frames in them that we're not all the same size and this was for some reason causing a runaway memory leak. I fixed the issue by adding `collection.Coalesce();`
after reading in the collection from the byte array

**Comment by dlemstra** [comment] 2021-06-15 21:08
Thanks for the info @nigtwisj. I will try to check if I can reproduce this in the future. Did you also test this with the latest version?

**Comment by dlemstra** [comment] 2021-07-03 19:43
And can you attach an image that I can use to reproduce this @nigtwisj?

**Comment by nigtwisj** [comment] 2021-07-03 20:04
Tried it with the latest version of the library and ran into the same issue. You can use this gif attached to reproduce it.[https://media1.tenor.com/images/a41df8ee310e15547bf5431cb16cc257/tenor.gif?itemid=20133682](url)

**Comment by dlemstra** [comment] 2021-07-04 09:25
Well it turns out this wasn't a memory leak after all. The problem is the input images. This is what happening with one of the frames:

```
frame.Width
1
frame.Height
1
frame.Page
{640x494+639+493}
```

But when you resize the image this changes into:

```
frame.Width
320
frame.Height
320
frame.Page
{204800x158080+204480+157760}
```

And the `CropToTiles` method will use the `Page` value in a loop value making steps of `64`. The memory is not leaking just a lot of memory is being used. And then when you `var tiles = g.ToArray()` you will be getting more than 25 tiles. So that would mean that you would need to also do this:

```C#
for (int i = tileSize; i < tiles.Length; i++)
{
    tiles[i].Dispose();
}
```

And it turns out that you actually found the fix for this by calling `collection.Coalesce()` after you have read it. And you probably should because you are resizing the input image to `320x320`.

**Closed by dlemstra** 2021-07-04 09:25 UTC
