### ISSUE TITLE
Failing to detect alpha channel in JPEG2000 files

### ISSUE THREAD

**Issue by AdamFrisby** [dlemstra/Magick.NET#1449] opened 2023-10-04 10:33 UTC
### Magick.NET version

13.3.0 Q16-AnyCPU

### Environment (Operating system, version and so on)

Amazon Linux 2

### Description

JPEG2000 files containing alpha channels no longer correctly set the image.hasAlpha attribute correctly.

The current version of MagickViewer correctly saves a PNG containing the alpha channel of the same test file.

### Steps to Reproduce

In the following code (it needs to handle multiple container types, hence the layering) hasAlpha no longer returns true, where previously it would.

Additionally, on further inspection, it also appears ChannelCount is now 3, not 4.

Environment: Amazon Linux 2, .NET Core 7 using NativeAOT.

```
                try
                {
                    using (MagickImage image = new MagickImage(tempFilename, MagickFormat.J2c))
                    {
                        hasAlpha = image.HasAlpha;
                        await WriteTemporaryImage(image, tempPng);
                    }
                }
                catch (ImageMagick.MagickImageErrorException ex1)
                {
                    try
                    {
                        using (MagickImage image = new MagickImage(tempFilename, MagickFormat.J2k))
                        {
                            hasAlpha = image.HasAlpha;
                            await WriteTemporaryImage(image, tempPng);
                        }
                    }
                    catch (MagickImageErrorException ec2)
                    {
                        using (MagickImage image = new MagickImage(tempFilename, MagickFormat.Jp2))
                        {
                            hasAlpha = image.HasAlpha;
                            await WriteTemporaryImage(image, tempPng);
                        }
                    }
                }
```

**Comment by dlemstra** [comment] 2023-10-04 16:16
Can you share an image that can be used to reproduce this?

**Comment by AdamFrisby** [comment] 2023-10-04 16:30
@dlemstra of course, my sample files I can't share on the internet, but I can send one another way if that is possible.

**Comment by dlemstra** [comment] 2023-10-05 06:36
I didn't see anything in your post that would say that your image was private? You could share it by email? It can be found on my profile page.

p.s. MagickViewer hasn't been updated in ages and I am considering to archive it and tell people to move to ImageGlass.

**Comment by AdamFrisby** [comment] 2023-10-05 13:24
Sent - thankyou! 

And yes, I was just using it as a test to prove the file itself wasn't broken since it was a convenient viewing application. :)

**Comment by dlemstra** [comment] 2023-10-05 19:25
We made some changes to ImageMagick recently when reading jpeg2000 images. There is a marker in the channel that specifies if it is an alpha channel or not. And it turns out that for your image the 4th channel is a meta channel instead of an alpha channel. And the current version of ImageMagick no longer reads that channel. I just pushed a patch to add support for reading that extra channel again. In the next version of Magick.NET you will be able to read that channel again but it won't be marked as an alpha channel.

What do you see in other viewers that makes you think that this image has an alpha channel?

**Comment by AdamFrisby** [comment] 2023-10-05 19:32
_Interesting_; the file definitely is _intended_ to have a alpha channel (it's a 3D texture), but it appears that whatever tool is writing the file is doing so improperly (I'm actually not surprised, most J2K libraries are not ... great). I've opened it in a few other JPEG2000 libraries which _do_ see it as a alpha channel (OpenJpeg, CSJ2K) but that may be them misinterpreting the spec, or just naively assuming 4 channels = RGBA.

Thank you so much for investigating and adding that patch.

**Comment by dlemstra** [comment] 2023-10-05 19:38
We could introduce an option that would always force the 4th channel to be an alpha channel? And then add this to the `Jp2ReadDefines`? But not sure what that define should be called.

**Comment by AdamFrisby** [comment] 2023-10-05 20:34
Yeah, that would be fantastic.

**Comment by dlemstra** [comment] 2023-10-06 04:57
The next release will have an `AssumeAlpha` property in the `Jp2ReadDefines` that you can use to automatically enable the alpha channel when the image has 2 or 4 channels.

**Comment by AdamFrisby** [comment] 2023-10-06 10:14
Very much appreciated - one last question from me, is there a beta version I can help test with?

**Comment by dlemstra** [comment] 2023-10-09 06:52
I was able to add some unit tests for this locally that use an that I created with the same alpha flag set to zero as in the image that your provided. But you can probably test this yourself with one of the build artifacts after I have updated ImageMagick in this repository in a couple days.

**Closed** 2023-12-11 21:36 UTC
