### ISSUE TITLE
Get System.AccessViolationException when concurrently read two or more large image files in x86 mode

### ISSUE THREAD

**Issue by linhnddev** [dlemstra/Magick.NET#1231] opened 2022-08-18 15:07 UTC
### Magick.NET version

Magick.NET-Q16-AnyCPU 12.0.1

### Environment (Operating system, version and so on)

WinUI3, Windows 11 - 21H2, 32GB RAM

### Description

When I tried to read two or more large image files (heic photos from iPhone), I got the System.AccessViolationException and the app crashed.
It only happens when debugging in x86 mode. I tried in x64 mode got no problem.

If file size is about 2-3MB, 4-5 concurrent tasks will causes the exception.
If file size is about 9-10MB, it happens with 2 concurrent tasks.

Don't know if it relates to the memory. The app memory shows in Task Manager is about 100-200MB

### Steps to Reproduce

- Set debug mode to x86
- Load two or more 9-10MB heic files concurrently.
- Wait for some seconds, AccessViolationException will occur

**Comment by dlemstra** [comment] 2022-08-18 15:15
I suspect that you are running out of memory. 32-bit processes have a hard limit and that might result in a memory allocation not working that is not properly handled.

If you can provide me with a small example and test images that I can use to reproduce this I can give you a better answer.

**Comment by linhnddev** [comment] 2022-08-18 15:29
Hi,

I have made a test project:
https://1drv.ms/u/s!AgNCgKvaRLYoifZ033-0ruF3rfAw0Q?e=HPaLSE

Hope you can reproduce the bug.

**Comment by dlemstra** [comment] 2022-08-18 20:24
Thanks for the sample and I was able to reproduce your issue. But it turns out that this is an issue in another library than ImageMagick. I opened a pull request for this but I also applied the patches to our local copy so this will be resolved in the next release of Magick.NET. But you will then get an exception that the image cannot be created due to memory allocation failure.

**Comment by linhnddev** [comment] 2022-08-19 00:42
Thank you 🙏!

**Closed** 2022-08-21 14:38 UTC
