### ISSUE TITLE
Reading SVG with `ReadAsync()` method and Inkscape PATH installed crashes the program

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#1660] opened 2024-06-24 23:14 UTC
### Magick.NET version

13.9.1

### Environment (Operating system, version and so on)

Windows 11 22H2

### Description

Hi Dirk!

When user installs Inkscape and adds its path to the system PATH, reading SVG image with `ReadAsync()` crashes the program, no exception thrown.

There are different behaviours when using different Magick.NET releases, so far I have tested with:
- `Magick.NET-Q16-HDRI-OpenMP-x64`: immediately crashes without any exception
- `Magick.NET-Q16-HDRI-AnyCPU`: extremely slow loading SVG file with high CPU usage

Originally reported https://github.com/d2phap/ImageGlass/issues/1935#issuecomment-2165762855 and https://github.com/d2phap/ImageGlass/issues/1944

### Steps to Reproduce

1. Install Inkscape using the [EXE format](https://inkscape.org/release/inkscape-1.3.2/windows/64-bit/exe/dl/)
2. Select option "Add Inkscape to the system PATH..." in the Inkscape Setup
<img src="https://github.com/dlemstra/Magick.NET/assets/3154213/3d3ff705-7dfe-44fc-a683-3e07bde1653b" width="400" />

3. You may need to restart computer for the Inkscape PATH take effect in VS2022
4. Download the sample project: [WinFormsApp5.zip](https://github.com/user-attachments/files/15962017/WinFormsApp5.zip)
5. Comment/Uncomment the methods `LoadImage()` and `LoadImageAsync()` to test. The problem happens with `LoadImageAsync()`

> [!NOTE]
> The problem is more obvious when loading multiple SVG files at the same time.

```cs
private void LoadImage()
{
    var filePath = @"test.svg";
    var imgM = new MagickImage();

    imgM.Read(filePath);
}

private async Task LoadImageAsync()
{
    var filePath = @"test.svg";
    var imgM = new MagickImage();

    await imgM.ReadAsync(filePath); // problem here
}


private void Form1_Load(object sender, EventArgs e)
{
    //LoadImage();
    _ = LoadImageAsync();
}
```

**Comment by dlemstra** [comment] 2024-06-26 05:40
Thanks for providing all this information and I am able to reproduce your issue. With a console application I was able to get some more information: 

> Fatal User Error 1002: Deadlock due to omp_set_lock being called on lock already owned by thread

I am not sure who is doing the locking but it feels like the combination of a .NET tread an OpenMP version of ImageMagick and inkscape breaks this.

I did however find a workaround for you. You can call `await File.ReadAllBytesAsync` and then pass those bytes to the `Read` method of Magick.NET. I am doing the same thing inside the `ReadAsync` method but doing that outside of that method fixes the issue.

**Comment by d2phap** [comment] 2024-06-26 09:52
Passing bytes to `Read()` fixes the issue. However, it's noticeably much slower (~3 - 4x), probably because ImageMagick uses Inkscape to render.

Is there any option to switch to the default ImageMagick SVG renderer?

**Comment by dlemstra** [comment] 2024-06-26 10:02
Which platform are you targeting? Inkscape produces much better results but maybe you should make this an option in your application? You can force the internal renderer by setting the format to `MagickFormat.Rsvg` but the result of Inkscape is much better than the `rsvg` renderer.

**Comment by d2phap** [comment] 2024-06-26 10:29
Currently, the default SVG renderer of ImageGlass is WebView2 because it offers more features: scaling on zooming, animation, hover interaction,.. (user can switch back to native render in the Settings).

I use Magick's SVG render for toolbar icons only. There are several of them and are loaded asynchronously in parallel (using `Parallel.ForEachAsync()`)

With Inkscape installed, in the sample project, it's somehow very slow to render. My settings are:
```cs
var s = new MagickReadSettings();
s.SetDefine("svg:xml-parse-huge", "true");
s.Format = MagickFormat.Svg;
s.BackgroundColor = MagickColors.Transparent;
s.Width = 400;
s.Height = 400;
```

If I changed to use `MagickFormat.Rsvg`, it becomes very fast again!
So for the toolbar SVG icons, I will just use `MagickFormat.Rsvg` because these icons are simple.

**Comment by dlemstra** [comment] 2024-06-26 11:02
Closing this then as I have no idea what inside Inkscape seems to be causing this.

**Closed by dlemstra** 2024-06-26 11:02 UTC

**Comment by d2phap** [comment] 2024-06-26 11:03
OK, thanks for investigating
