### ISSUE TITLE
Invalid argument @ error/blob.c/OpenBlob/3335 on PDF image

### ISSUE THREAD

**Issue by briankitt** [dlemstra/Magick.NET#168] opened 2018-02-20 20:02 UTC
I am trying to open a PDF image to interrogate the size.

I am getting the error above.  Image is attached.
[Rise Pizzeria Front.pdf](https://github.com/dlemstra/Magick.NET/files/1741669/Rise.Pizzeria.Front.pdf)

Stack trace:
at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings)
at ImageMagick.MagickImage..ctor(String fileName)

**Comment by dlemstra** [comment] 2018-02-20 20:41
The following works for me:
```
using (var image = new MagickImage(@"i:/pdf/Rise.Pizzeria.Front.pdf"))
{
}
```

Which version of Ghostscript are you using?

**Comment by briankitt** [comment] 2018-02-20 22:03
I was on 9.19.

I upgraded to 9.22

Same issue.  My code is identical to yours in every way, except drive
letter.

Does anything need to be done after upgrading ghost script?  (reboot, etc).

**Comment by dlemstra** [comment] 2018-02-20 22:36
I am not sure but I think you also need to uninstall the old version. I remember that an install of a newer version does not remove the old one.

**Comment by briankitt** [comment] 2018-02-21 00:51
Yes, you are correct, and I did uninstall it before I tried.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by briankitt** [comment] 2018-02-22 14:30
Ok.  I rebooted the server last night.  This problem still exists.

I am running the most current version of Magick.NET.   I went to get hub to
be sure I am current, and I am at the most current version.

I upgraded to latest Ghost script, but I did uninstall prior version.


But, now when I open the image, I get a slightly different variation of the
same error. I get Invalid argument @ error/blob.c/OpenBlob/3353

What else can I try.

**Comment by dlemstra** [comment] 2018-02-22 14:57
Can you provide me with a small code sample that I can use to reproduce the issue? Maybe a github repo with a sample program? I suspect it is related to how you are using Magick.NET.

**Comment by briankitt** [comment] 2018-02-22 15:19
Here's the part where this gets tricky.  I do nothing more than a new
MagickImage('image") and it fails, BUT!!!

On my windows 10 machine, it works perfect.
On my production server, it fails.  Windows server 2012 Standard.

So it's something related to my production server.  I just can't figure out
what is different.

This server was built about 4 or 5 years ago. And everything else works
fine in MagickImage, only this one PDF.  We have other PDF's that work fine.

All maintenance is current (which is not always a good thing).

Any ideas of anything I could look at?

**Comment by dlemstra** [comment] 2018-02-22 16:36
Maybe there is still a reference to the old Ghostscript versions in your registry? Magick.NET uses the registry to find Ghostscript. Do you have the same platform (x64/x8) for Ghostscript and your application pool in both situations?

**Comment by briankitt** [comment] 2018-02-22 17:22
This is what I have.  I did instgall both 64 and 32 bit versions.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\GPL Ghostscript]

[HKEY_LOCAL_MACHINE\SOFTWARE\GPL Ghostscript\9.22]
"GS_DLL"="C:\\Program Files\\gs\\gs9.22\\bin\\gsdll64.dll"
"GS_LIB"="C:\\Program Files\\gs\\gs9.22\\bin;C:\\Program
Files\\gs\\gs9.22\\lib;C:\\Program Files\\gs\\gs9.22\\fonts"

**Comment by briankitt** [comment] 2018-02-22 17:46
I have an interesting update.

I was talking to my user.  They said this just stopped working.  PDF images
that worked fine a few weeks ago, no longer work now.

In the last few weeks:
I've updated Magick.NET to the latest version.
I updated ghost script AFTER the problem, not BEFORE.
I always keep current on all server updates, and I did apply server updates
recently.
.NET has not changed on the project.  The project is .NET 4.7, MVC 5

**Comment by dlemstra** [comment] 2018-02-23 11:37
Maybe you can get more info when you add debug logging? Info on how to do that can be found here: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/DetailedDebugInformation.md

**Comment by briankitt** [comment] 2018-02-23 14:44
Excellent !  This is the same image I sent you.  I store them on the disk
with a guid, so I don't have to worry about name collisions.

2018-02-23T07:43:00-07:00 0:02.270 2.266u 7.0.7 Policy w3wp.exe[7816]:
policy.c/IsRightsAuthorized/609/Policy
  Domain: Path; rights=Read;
pattern="D:\DocumentStore\Boomerang\Test\PartnerBackground\D:\DocumentStore\Boomerang\Test\PartnerBackground\137bdf65-afce-4bb4-bd59-c75798b03342.pdf"
...2018-02-23T07:43:00-07:00 0:02.272 2.266u 7.0.7 Locale w3wp.exe[7816]:
locale.c/GetLocaleOptions/827/Locale
  Searching for locale file:
"C:\Users\boomerang\AppData\Local\Temp\Magick.NET.net40.7.4.1.0\locale.xml"2018-02-23T07:43:00-07:00
0:02.272 2.266u 7.0.7 Locale w3wp.exe[7816]:
locale.c/GetLocaleOptions/827/Locale
  Searching for locale file:
"c:\windows\system32\inetsrv\locale.xml"2018-02-23T07:43:00-07:00 0:02.273
2.266u 7.0.7 Locale w3wp.exe[7816]: locale.c/GetLocaleOptions/827/Locale
  Searching for locale file: "locale.xml"2018-02-23T07:43:00-07:00 0:02.273
2.266u 7.0.7 Locale w3wp.exe[7816]: locale.c/GetLocaleOptions/827/Locale
  Searching for locale file:
"C:\Users\boomerang\AppData\Local\ImageMagick\locale.xml"2018-02-23T07:43:00-07:00
0:02.273 2.266u 7.0.7 Configure w3wp.exe[7816]:
locale.c/LoadLocaleCache/1179/Configure
  Loading locale configure file
"C:\Users\boomerang\AppData\Local\Temp\Magick.NET.net40.7.4.1.0\locale.xml"
...2018-02-23T07:43:00-07:00 0:02.274 2.266u 7.0.7 Configure
w3wp.exe[7816]: locale.c/LoadLocaleCache/1179/Configure
  Loading locale configure file
"C:\Users\boomerang\AppData\Local\Temp\Magick.NET.net40.7.4.1.0\english.xml"
...2018-02-23T07:43:00-07:00 0:02.350 2.344u 7.0.7 Configure
w3wp.exe[7816]: locale.c/LoadLocaleCache/1179/Configure
  Loading locale configure file "locale.xml" ...2018-02-23T07:43:00-07:00
0:02.351 2.344u 7.0.7 Exception w3wp.exe[7816]:
blob.c/OpenBlob/3353/Exception
  unable to open image
'D:\DocumentStore\Boomerang\Test\PartnerBackground\D:\DocumentStore\Boomerang\Test\PartnerBackground\137bdf65-afce-4bb4-bd59-c75798b03342.pdf':
Invalid argument2018-02-23T07:43:00-07:00 0:02.351 2.344u 7.0.7 Cache
w3wp.exe[7816]: cache.c/DestroyPixelCache/955/Cache
  destroy 2018-02-23T07:43:00-07:00 0:02.352 2.344u 7.0.7 Policy
w3wp.exe[7816]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Coder; rights=Read; pattern="PDF" ...2018-02-23T07:43:00-07:00
0:02.352 2.344u 7.0.7 Policy w3wp.exe[7816]:
policy.c/IsRightsAuthorized/609/Policy
  Domain: Path; rights=Read;
pattern="D:\DocumentStore\Boomerang\Test\PartnerBackground\D:\DocumentStore\Boomerang\Test\PartnerBackground\137bdf65-afce-4bb4-bd59-c75798b03342.pdf"
...2018-02-23T07:43:00-07:00 0:02.352 2.344u 7.0.7 Exception
w3wp.exe[7816]: blob.c/OpenBlob/3353/Exception
  unable to open image
'D:\DocumentStore\Boomerang\Test\PartnerBackground\D:\DocumentStore\Boomerang\Test\PartnerBackground\137bdf65-afce-4bb4-bd59-c75798b03342.pdf':
Invalid argument2018-02-23T07:43:00-07:00 0:02.352 2.344u 7.0.7 Cache
w3wp.exe[7816]: cache.c/DestroyPixelCache/955/Cache
  destroy 2018-02-23T07:43:00-07:00 0:02.359 2.359u 7.0.7 Cache
w3wp.exe[7816]: cache.c/DestroyPixelCache/955/Cache
  destroy

**Comment by dlemstra** [comment] 2018-02-23 16:04
It looks like you are supplying an incorrect path but maybe this is an issue in the ImageMagick library? The path looks incorrect: `D:\DocumentStore\Boomerang\Test\PartnerBackground\D:\DocumentStore\Boomerang\Test\PartnerBackground\137bdf65-afce-4bb4-bd59-c75798b03342.pdf`.

p.s. I did not receive an image, not sure if I need it though.

**Comment by briankitt** [comment] 2018-02-23 16:45
I will check to be 100% sure.

**Comment by briankitt** [comment] 2018-02-23 16:53
Dang, you are absolutely right.

So sorry to have bothered you, this is clearly not your issue.  This has
been working fine for more than a year.  Now I need to figure out what
changed and broke this.

Thank you so much for your help!  I'll have to send another donation your
way!

**Comment by dlemstra** [comment] 2018-02-23 17:07
Still possible that we broke something in our code. Can you close this issue if you have confirmed this was a problem in your code?

**Closed** 2018-02-23 20:12 UTC
