### ISSUE TITLE
MagickImage.Statistics().GetChannel(PixelChannel.Composite) returns all zeros.

### ISSUE THREAD

**Issue by DarinMacRae** [dlemstra/Magick.NET#869] opened 2021-02-24 16:14 UTC
### Description
I recently upgraded from 7.22.0 to 7.23.2 and see that making calls to MagickImage.Statistics().GetChannel(PixelChannel.Composite) returns all zeros. In 7.22.0 it returns useful values.

### Steps to Reproduce
I narrowed down the "break" to 7.22.2.1.
If I install 7.22.2.0 I get useful values. If I install 7.22.2.1 it returns all zeros.

![image](https://user-images.githubusercontent.com/3474753/109029650-e891ff00-7677-11eb-8e3b-ccec0ad54766.png)

### System Configuration
I have a Linqpad 6 query that I use to dump out statistics on the composite channel.

```
void Main()
{
    const string path = @"S:\data\Photos";
    var files = new DirectoryInfo(path).GetFiles("*.jpg");
    var data = files
        .Select(f => GetProperties(f))
        .OrderBy(_ => _.Colors)
        .ToList()
        ;
        
    data.Dump();
    
    LINQPad.Extensions.Dump(data[0]);
}

void Dump(string file)
{
    using (var image = new MagickImage(file))
	{
		image.TotalColors.Dump();
		image.Statistics().GetChannel(PixelChannel.Composite).Dump();
	}
}

dynamic GetProperties(FileInfo file)
{
    using (var image = new MagickImage(file))
    {
        var colors = image.TotalColors;
        var channel = image.Statistics().GetChannel(PixelChannel.Composite);
        return new 
        {
            file.Name,
            Colors = colors, 
            //Depth = channel.Depth,
            Entropy = channel.Entropy, 
            Kurtosis = channel.Kurtosis, 
            Max = channel.Maximum,
            Mean = channel.Mean,
            //Min = channel.Minimum,
            Skewness = channel.Skewness,
            StdDev = channel.StandardDeviation,
            Sum = channel.Sum,
            Sum2 = channel.SumSquared,
            Sum3 = channel.SumCubed,
            Sum4 = channel.SumFourthPower,
            Var = channel.Variance

        };
    }
}
```
7.22.2.0:
![image](https://user-images.githubusercontent.com/3474753/109030040-4fafb380-7678-11eb-85c4-764d9e9f020b.png)

7.22.2.1:
![image](https://user-images.githubusercontent.com/3474753/109029751-00698300-7678-11eb-944c-7bc01d597065.png)

**Comment by dlemstra** [comment] 2021-02-24 16:22
Do you have a test image that I can use to reproduce this?

**Comment by DarinMacRae** [comment] 2021-02-24 16:29
Any image should reproduce it but here's one from Lorum Picsum I just reproduced it with.

![lorumpicsum](https://user-images.githubusercontent.com/3474753/109032299-5c350b80-767a-11eb-9e39-77cbfbe61b01.jpg)

**Comment by dlemstra** [comment] 2021-02-24 19:57
This issues was caused by a change that increased the maxmimum number of available channels. Will add some tests to make sure we won't hit this problem in the future and a fix should become available pretty soon.

**Comment by dlemstra** [comment] 2021-02-28 19:27
Just published a new release that includes a fix for this.

**Closed by dlemstra** 2021-02-28 19:27 UTC
Labels: bug
