### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by ktngoykalolo** [dlemstra/Magick.NET#22] opened 2016-11-04 20:51 UTC
Hello,
I would like to include support for Xamarin,
but I need a bit of guidance.

**Comment by dlemstra** [comment] 2016-11-05 10:16
It would be really cool if you could add Xamarin support. To make this possible you will need to create a build script that creates lib files that can be used on IPhone/Android. You can take a look what happens under Windows here: https://github.com/dlemstra/Magick.NET/blob/master/Building.md. Instead of BuildAll.cmd there should be a shell script that statically builds the binaries for IPhone/Anroid.

**Comment by ktngoykalolo** [comment] 2016-11-05 10:34
Hi Dirk,
thanks. I will look at that and revert to you.

**Comment by ktngoykalolo** [comment] 2016-11-15 14:03
Hello Dirk,
i am having issues building the libraries,
could you help ?

**Comment by dlemstra** [comment] 2016-11-15 14:37
My primary expertise is Windows and not Unix/Linux. But I think the goal should be building each library step by step. Do you have a script of what you have done so far?

**Comment by ktngoykalolo** [comment] 2016-11-15 14:42
well still trying to build the script for the main version on Windows.
for Xamarin it should be the same process but I want to target see if I can do it with a PCL.

**Comment by ktngoykalolo** [comment] 2017-01-26 09:57
Hello, I am still encountering the following error : LNK1104, unable to find file "bzib.lib" 
I checked the files and it is there.

**Comment by ktngoykalolo** [comment] 2017-07-05 10:39
please keep this open. I will work on this when I got some free time.

**Comment by ktngoykalolo** [comment] 2017-09-20 05:18
Hello, I have not forgotten about this. Migrating this library will be easier now with .net standard 2.0 and the new windows compatibility pack announced yesterday at dotnet conf. 2017.

**Comment by ktngoykalolo** [comment] 2017-09-20 05:29
Still have some timing issues to work on this.

**Comment by MPusch** [comment] 2018-03-29 12:11
Hello, 

what is the actual status? I use ImageMagick with success in a Xamarin project when running as UWP. When using on the IPhone I fail.
I take a photo with the internal camera, which is working fine and try then to create a MagickImage within a .NET Standard 2.0 project:
`ImageMagick.MagickImage image = new ImageMagick.MagickImage(new FileInfo(photo.Path));`
This leads to
`The type initializer for 'NativeMagickSettings' threw an exception.`
I tried Magick.NET-Q8-AnyCPU (7.4.3) and Magick.NET-Q16-AnyCPU (7.4.3) with no success.
Any idea how to solve this or is there still no full implementation for Xamarin?

**Comment by ktngoykalolo** [comment] 2018-03-29 15:40
busy with other priorities, if you can take this on, then go ahead

**Comment by ITFactoryAUT** [comment] 2018-07-26 21:58
The issue @MPusch described is still unsolved. With the current version of Magick.NET (7.5.0.1) I get the exact error.
But when you look at the internal exception "Failed to load dll Magick.NET-Q8-AnyCPU.dll". But I have absolutely no idea why this happens.

**Comment by ktngoykalolo** [comment] 2020-02-12 16:31
Shouldn't the core C++ library made compatible with .net standards ? Is there an easy way to do that ?

**Comment by dlemstra** [comment] 2020-02-13 08:08
Not sure what you are asking? The native C library of Magick.NET (called Magick.Native) works on the Windows, Linux and MacOS.

**Comment by snechaev** [comment] 2020-03-17 11:53
I was able to run Magick.NET on the Xamarin.Mac runtime on the Mac OS X with the following steps:
1. Create a Xamarin.Mac Cocoa project (targeting Xamarin.Mac Modern or Xamarin.Mac Full 4.8)
2. Add Magick.NET-Q8-x64 Nuget package and some Magick.NET-related test code.
3. Build and try to run - you will get the error described above (The type initializer for 'NativeMagickSettings' threw an exception.)
4. Open output folder of the project, then open the bundle (in Finder, right click and select Show package contents) and go to the Contents/MonoBundle folder (so, the full path will be <project root>/bin/Debug/<target_app_name>.app/Contents/MonoBundle
5. Copy file <project root>/packages/Magick.NET-Q8-x64.7.15.4/runtimes/osx-x64/native/Magick.Native-Q8-x64.dll.dylib to the to the MonoBundle folder, then rename the copy to the Magick.Native-Q8-x64.dll (drop .dylib)
6. Run the bundle - it should work fine. 
7. After full rebuild you will need to copy file again. But after partial rebuild all still works fine.

So, the conclusion is:
* Looks like both managed and native parts of Magick.NET work fine with xamarin.mac environment.
* The problem is somewhere in build system or in nuget platform selection. 

Note: this solution will not work on Iphone/android because of lack of the native ImageMagick libraries built for these platforms. But on Mac OS it works fine.

**Comment by dlemstra** [comment] 2020-07-20 05:43
Closing this for now.

**Closed by dlemstra** 2020-07-20 05:43 UTC
Labels: enhancement, help wanted

**Comment by MichalJan008** [comment] 2021-05-12 17:14
Hi, the code works brilliant on Xamarin.UWP, but on Xamarin.Android (and probably iOS as well) it fails with communicate 
System.DllNotFoundException Magick.Native-Q8-x64.dll assembly:<unknown assembly> type:<unknown type> member:(null). 

Could anyone help to create the mentioned build scripts or Xamarin.iOS and Xmarin.Androind ? 
 
@snechaev , you wrote that: 
_"Note: this solution will not work on Iphone/android because of lack of the native ImageMagick libraries built for these platforms."_ 
As of now on the homepage of the ImageMagick project they state that there is official support for iOS and Android. 
_"(The current release is ImageMagick 7.0.11-12. It runs on Linux, Windows, Mac Os X, iOS, Android OS, and others.)"_
Do you think that the workaround you did with Mac could also work for iOS and Android ?

**Comment by snechaev** [comment] 2021-05-12 18:25
@MichalJan008, I don't know much about imagemagick internals and I did not tryed this for ios/android. But I can assume that if you will get platform-specific IM binaries (.so for android and .dylib for iOS), the approach described above may work. But you still can get issues with emulators, as iOS emulator is actually x86 (and you will pack arm-targeted dylib).
