### ISSUE TITLE
Pink image after extracting pages from multipage tiff

### ISSUE THREAD

**Issue by hade94** [dlemstra/Magick.NET#946] opened 2021-06-03 21:13 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
After updating from 7.21.0 to 7.24.1 tiff files are not converted to jpg with the correct colors. All color pages (True Color, YCBCR) that are exported have a pink tone to it.

### Steps to Reproduce
```c#
using (MagickImageCollection layers = new MagickImageCollection(memStream))
{
      foreach (var layer in layers)
      {
	      using (var memoryStream = new MemoryStream())
		      {
			     layer.Write(memoryStream, MagickFormat.Jpeg);
      
		      }
	      }
      }
```
```
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 1984x2777+0+0
  Resolution: 240x240
  Print size: 8.26667x11.5708
  Units: PixelsPerInch
  Type: TrueColor
  Base type: TrueColor
  Endianess: LSB
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 5509568
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 232.99 (0.913687)
      standard deviation: 45.5867 (0.178771)
      kurtosis: 7.19807
      skewness: -2.73348
      entropy: 0.47031
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 233.537 (0.915833)
      standard deviation: 47.0883 (0.18466)
      kurtosis: 7.88032
      skewness: -2.8817
      entropy: 0.459614
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 235.167 (0.922225)
      standard deviation: 43.2472 (0.169597)
      kurtosis: 8.2058
      skewness: -2.90587
      entropy: 0.453397
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 233.898 (0.917248)
      standard deviation: 45.335 (0.177784)
      kurtosis: 7.80675
      skewness: -2.84705
      entropy: 0.461107
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 1984x2777+0+0
  Dispose: Undefined
  Iterations: 0
  Scene: 2 of 5
  Compression: JPEG
  Orientation: TopLeft
  Properties:
    date:create: 2021-06-01T23:09:26+02:00
    date:modify: 2019-12-09T03:07:50+01:00
    signature: e0920752af36090512e954b280f241accd193c3da85e178fc1fca6c724f69fa0
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: YCBCR
    tiff:rows-per-strip: 2777
    tiff:software: Kofax standard Multi-Page TIFF Storage Filter v3.03.000
    tiff:subfiletype: PAGE
    tiff:timestamp: 2019:12:09 03:07:50
  Artifacts:
    filename: x.TIF
    verbose: true
  Tainted: False
  Filesize: 1.556MB
  Number pixels: 5.51M
  Pixels per second: 6.638MB
  User time: 1.160u
  Elapsed time: 0:01.829
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
```
### System Configuration
Using the Q8 Any CPU Version of the library inside a mcr.microsoft.com/dotnet/aspnet:5.0 docker base image.

Any ideas guys?

Thanks

**Comment by dlemstra** [comment] 2021-06-04 04:50
Can you share the tiff file that csn be used to reproduce this issue?

**Comment by hade94** [comment] 2021-06-04 12:07
I will share the file this weekend.

**Comment by hade94** [comment] 2021-06-08 14:52
[Sample001.zip](https://github.com/dlemstra/Magick.NET/files/6617531/Sample001.zip)

**Comment by hade94** [comment] 2021-06-09 10:13
[Bastian-multitif-farbe.zip](https://github.com/dlemstra/Magick.NET/files/6622956/Bastian-multitif-farbe.zip)

**Comment by dlemstra** [comment] 2021-06-11 17:09
Thanks for providing the file. It turns out that ImageMagick had a check missing when reading this file. I pushed a patch to resolve this and this should be fixed in the next release of Magick.NET.

**Comment by mohamedhamza7** [comment] 2021-06-11 18:40
Dear Dirk, 

First, thank you so much for your efforts for develop and maintain this library.

I also have the same issue after turn from version Q8-x86.7.14.4.0 to Q16-x86.7.24.1, and i do the upgrade because i noticed that the size of TIFF files (with JPEG compression) increased after add some text on the first page of the file and for testing purpose I just read and write the file with the below code,

`            using (var src = new MagickImageCollection(srcFilePath))
            {
                using (var des = new MagickImageCollection())
                {
                    foreach (var page in src)
                    {
                        page.Settings.Format = page.Format;
                        page.Settings.Compression = page.Compression;

                        des.Add(page);

                    }
                    des.Write(desFilePath);
                }
            }`


Kindly is there is a way to keep the file size the same?

[TIFFFiles.zip](https://github.com/dlemstra/Magick.NET/files/6640379/TIFFFiles.zip)

**Comment by dlemstra** [comment] 2021-06-12 07:03
I don't think you can keep the same size but also setting the colorspace of the image to YCbCr seems to reduce the size of the file: `image.ColorSpace = ColorSpace.YCbCr;`.

**Comment by dlemstra** [comment] 2021-06-27 09:48
Can you test this again with the latest release @mohamedhamza7, and close this issue when the pink colors are gone?

**Closed** 2021-07-03 19:43 UTC

**Comment by hade94** [comment] 2021-07-06 16:20
@dlemstra Sorry for my late response, i've tested this and it works fine. Issue resolved. Thanks!
