### ISSUE TITLE
MagickImage.Deskew locks the application.

### ISSUE THREAD

**Issue by korhun** [dlemstra/Magick.NET#114] opened 2017-10-17 06:08 UTC
Hi, 
First of all, thank you for your efforts for this great library.

I have an annoying issue that I could not found a solution:
* I have 8 threads.
* Each thread is doing TextClean processes on multipage tiff images each having 70-160 pages. Each page is around 300dpi with A4 size.
* The text clean processes work just great on many data, however in some cases, "MagickImage.Deskew" does not finish what it is doing for hours (even weeks!, my friends tested it). 
* The application do respond. 
* Application CPU use is ~%90. Memory use is stable and there is available physical memory (in some cases at least 5GB available.) (The application seems to be working without problem but every thread are waiting for the Deskew to be finished, no return and we keep on waiting.)
* The hanging does not happen on the same pages of the files.
* The text clean process does nothing special; its a modified version (doing less) of TextClean script available on NuGet. 
* The multipage processing is something like this:

 ```
               using (MagickImageCollection coll = new MagickImageCollection(input))
                {
                    for (int i = 0; i < coll.Count; i++)
                    {
                        MagickImage img = (MagickImage)coll[i];
                            clean(img);
                    }                    
                    coll.Write(target);
                }
```
* If we process each file on single thread there is no problem (I am not exactly sure of this; could not make enough tests on that.)
* I'have tried on Q8, Q16 - AnyCPU; Q8-OpenMP x64,  on 7.0.7.700, 7.0.6.1002, 7.0.6.100; and maybe some other combinations that I don't remember now. I am testing older releases now.
* Tested on Windows 8.1 x64, Windows 10 x64, >=16GB physical memory computers. Some of them has SSD.

Any help is very appreciated, since TextClean made a big difference on success ratio; however I cannot use this library if I can't find a solution for this.

**Comment by korhun** [comment] 2017-10-17 11:15
I have tested Magick.NET-Q8-AnyCPU 7.0.3.0 and found no problems on my computer. We'll make some futher tests with that release.

**Comment by dlemstra** [comment] 2017-10-17 13:28
Is it possible to create a test project that demonstrates the issue? And are you aware that you require a license for the TextCleaner script?

**Comment by korhun** [comment] 2017-10-17 17:29
Thank you for your response and license warning. 

I cannot share the data and my engine code; but I suppose I can prepare a simple example project with some other data. I will give it a try when I find time. 

However, I think there is enough clue to find the bug: MagicImage.Deskew hangs after many calls (>10000) on 8 to16 threads simultanously with 300dpi A4 images. And this locking does not occur on Magick.NET-Q8-AnyCPU 7.0.3; (yet at least)

**Comment by dlemstra** [comment] 2017-10-17 19:04
I did a quick check of the deskew code and I don't see anything in there that could have issue with multithreaded calls. I don't need/want your while engine. I just need a small program that demonstrates the issue. The issue might be caused by something else in your code before you call Deskew.

**Comment by korhun** [comment] 2017-10-26 07:25
Last night I have tried this code with Windows 10 x64 16GB Ram on Release mode with Q16 Any CPU 7.0.7.700:
```

    class Program
    {
        static void Main(string[] args)
        {
            string[] files = Directory.GetFiles(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "data"), "*.*");
            for (int i = 0; i <= 1000; i++)
            {
                Stopwatch w = Stopwatch.StartNew();
                Parallel.ForEach(files, (fn) =>
                {
                    process(fn);
                });
                w.Stop();
                Console.WriteLine(string.Format("try {0} - {1} minutes", i.ToString(), w.ElapsedMilliseconds / (60000d)));
            }
            Console.WriteLine("finished");
            Console.ReadKey();
        }

        private static void process(string fn)
        {
            using (MagickImageCollection coll = new MagickImageCollection(fn))
            {
                for (int i = 0; i < coll.Count; i++)
                {
                    MagickImage img = (MagickImage)coll[i];
                    img.Deskew(new Percentage(40d));
                }
            }
        }
    }

```
 
The output after 12 hours is:
> try 0 - 5.7054 minutes
> try 1 - 24.4570666666667 minutes
> try 2 - 26.9191666666667 minutes
> try 3 - 25.53815 minutes
> try 4 - 26.8812833333333 minutes
> try 5 - 26.7545 minutes
> try 6 - 25.5957666666667 minutes
> try 7 - 26.9355666666667 minutes
> try 8 - 26.91755 minutes
> try 9 - 26.8799333333333 minutes
> try 10 - 26.7845666666667 minutes

The application is still running with %26 CPU usage. 

I have used 2 multi page tiff files, containing 58 and 74 pages. Pages are around 2500x3500 pixels. Files are on my local SSD disk. I'm not sure I may be allowed to send you the files, but I will ask permission to share them with you if you require them.

Thanks in advance.

**Comment by korhun** [comment] 2017-10-26 07:32
I got a feeling that Windows might have gone to sleep mode. I'll make another test and ensure that it does not. Don't pay atttention to my previous comment.

**Comment by dlemstra** [comment] 2017-10-26 08:40
Thanks for helping me reproduce this 👍 Will have some time to look at this tomorrow if you can reproduce this.

**Comment by korhun** [comment] 2017-10-29 06:04
Hello, I made another test. 

```

        static void Main(string[] args)
        {
            string[] files = Directory.GetFiles(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "data"), "*.*");
            for (int i = 0; i <= 100; i++)
            {
                Stopwatch w = Stopwatch.StartNew();
                foreach(string fn in files)
                {
                    process(fn);
                }
                w.Stop();
                Console.WriteLine(string.Format("try {0} - {1} minutes", i.ToString(), w.ElapsedMilliseconds / (60000d)));
            }
            Console.WriteLine("finished");
            Console.ReadKey();
        }

        private static void process(string fn)
        {
            using (MagickImageCollection coll = new MagickImageCollection(fn))
            {
                Parallel.For(0, coll.Count, (i) =>
                {
                    MagickImage img = (MagickImage)coll[i];
                    img.Deskew(new Percentage(40d));
                });
            }
        }

```

This code runned on my pc for more than 36 hours. There was no single line printed on the console output. Now I am sure that my system did not go to sleep. I also check the windows events and confirmed that it did not sleep so this time I cannot blame our 2 cats in the office :) Previous code was running on 2 threads (as there are 2 multipage tiff files) but this one is running a lot of threads using %96-98 of the CPU all the time. I have attached and put a break point and waited for some time; no stop occured. 
I hope I'm not doing something wrong and this information help you. Tomorrow I'll try to get permission to send you the tiff files. Thank you very much.

**Comment by korhun** [comment] 2017-10-30 03:49
I've made another test with this code, on the same data:

```
        static void Main(string[] args)
        {
            string[] files = Directory.GetFiles(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "data"), "*.*");
            string txtFileName = Path.GetTempFileName() + "_magick.txt";
            if (File.Exists(txtFileName))
                File.Delete(txtFileName);

            Stopwatch wTotal = Stopwatch.StartNew();
            for (int i = 0; i <= 10000; i++)
            {
                Stopwatch w = Stopwatch.StartNew();
                foreach(string fn in files)
                {
                    process(fn, (string txt)=>
                    {
                        string txt1 = string.Format("i={0} - {1} - {2}", i, getTime(wTotal), txt);
                        Console.WriteLine(txt1);
                    });
                }
                w.Stop();
                string msg = string.Format("*******ITERATION {0} FINISHED - iteration time: {1} - total time: {2}", i, getTime(w), getTime(wTotal));
                Console.WriteLine(msg);
                if (!File.Exists(txtFileName))
                    File.WriteAllLines(txtFileName, new string[] { msg });
                else
                    File.AppendAllLines(txtFileName, new string[] { msg });
            }
            wTotal.Stop();
            Console.WriteLine("all finished - " + getTime(wTotal));
            System.Diagnostics.Process.Start(txtFileName);
            Console.ReadKey();
        }
        private static string getTime(Stopwatch w)
        {
            return string.Format("{0} minutes", (w.ElapsedMilliseconds / (60000d)).ToString("N2"));
        }

        private static void process(string fn, Action<string> action)
        {
            using (MagickImageCollection coll = new MagickImageCollection(fn))
            {
                Parallel.For(0, coll.Count, (j) =>
                {
                    MagickImage img = (MagickImage)coll[j];
                    img.Deskew(new Percentage(40d));
                    action(string.Format("j={0} - file: {1}", j, Path.GetFileName(fn)));
                });
            }
        }

```
It ran more than 12 hours. The CPU use is now %12 and the file output is:

> 
> *******ITERATION 0 FINISHED - iteration time: 2.35 minutes - total time: 2.35 minutes
> *******ITERATION 1 FINISHED - iteration time: 2.48 minutes - total time: 4.82 minutes
> *******ITERATION 2 FINISHED - iteration time: 2.34 minutes - total time: 7.17 minutes
> *******ITERATION 3 FINISHED - iteration time: 2.29 minutes - total time: 9.46 minutes
> *******ITERATION 4 FINISHED - iteration time: 2.38 minutes - total time: 11.84 minutes
> *******ITERATION 5 FINISHED - iteration time: 2.38 minutes - total time: 14.23 minutes
> *******ITERATION 6 FINISHED - iteration time: 2.37 minutes - total time: 16.59 minutes
> *******ITERATION 7 FINISHED - iteration time: 2.32 minutes - total time: 18.92 minutes
> *******ITERATION 8 FINISHED - iteration time: 2.32 minutes - total time: 21.23 minutes
> *******ITERATION 9 FINISHED - iteration time: 2.35 minutes - total time: 23.59 minutes
> *******ITERATION 10 FINISHED - iteration time: 2.36 minutes - total time: 25.95 minutes
> *******ITERATION 11 FINISHED - iteration time: 2.36 minutes - total time: 28.32 minutes
> *******ITERATION 12 FINISHED - iteration time: 2.33 minutes - total time: 30.64 minutes
> *******ITERATION 13 FINISHED - iteration time: 2.33 minutes - total time: 32.97 minutes
> *******ITERATION 14 FINISHED - iteration time: 2.30 minutes - total time: 35.27 minutes
> *******ITERATION 15 FINISHED - iteration time: 2.31 minutes - total time: 37.58 minutes
> *******ITERATION 16 FINISHED - iteration time: 2.33 minutes - total time: 39.92 minutes
> *******ITERATION 17 FINISHED - iteration time: 2.31 minutes - total time: 42.23 minutes
> *******ITERATION 18 FINISHED - iteration time: 2.39 minutes - total time: 44.61 minutes
> *******ITERATION 19 FINISHED - iteration time: 2.37 minutes - total time: 46.98 minutes
> *******ITERATION 20 FINISHED - iteration time: 2.37 minutes - total time: 49.35 minutes
> *******ITERATION 21 FINISHED - iteration time: 2.37 minutes - total time: 51.72 minutes
> *******ITERATION 22 FINISHED - iteration time: 2.36 minutes - total time: 54.08 minutes
> *******ITERATION 23 FINISHED - iteration time: 2.33 minutes - total time: 56.41 minutes
> *******ITERATION 24 FINISHED - iteration time: 2.32 minutes - total time: 58.73 minutes
> *******ITERATION 25 FINISHED - iteration time: 2.32 minutes - total time: 61.06 minutes
> *******ITERATION 26 FINISHED - iteration time: 2.33 minutes - total time: 63.38 minutes
> *******ITERATION 27 FINISHED - iteration time: 2.33 minutes - total time: 65.72 minutes
> *******ITERATION 28 FINISHED - iteration time: 2.43 minutes - total time: 68.15 minutes
> *******ITERATION 29 FINISHED - iteration time: 2.37 minutes - total time: 70.51 minutes
> *******ITERATION 30 FINISHED - iteration time: 2.35 minutes - total time: 72.86 minutes
> *******ITERATION 31 FINISHED - iteration time: 2.33 minutes - total time: 75.19 minutes
> *******ITERATION 32 FINISHED - iteration time: 2.32 minutes - total time: 77.51 minutes
> *******ITERATION 33 FINISHED - iteration time: 2.36 minutes - total time: 79.87 minutes
> *******ITERATION 34 FINISHED - iteration time: 2.31 minutes - total time: 82.18 minutes
> *******ITERATION 35 FINISHED - iteration time: 2.28 minutes - total time: 84.46 minutes
> *******ITERATION 36 FINISHED - iteration time: 2.35 minutes - total time: 86.81 minutes
> *******ITERATION 37 FINISHED - iteration time: 2.46 minutes - total time: 89.28 minutes
> *******ITERATION 38 FINISHED - iteration time: 2.35 minutes - total time: 91.63 minutes
> *******ITERATION 39 FINISHED - iteration time: 2.43 minutes - total time: 94.06 minutes
> *******ITERATION 40 FINISHED - iteration time: 2.32 minutes - total time: 96.38 minutes
> *******ITERATION 41 FINISHED - iteration time: 2.32 minutes - total time: 98.70 minutes
> *******ITERATION 42 FINISHED - iteration time: 2.34 minutes - total time: 101.04 minutes
> *******ITERATION 43 FINISHED - iteration time: 2.33 minutes - total time: 103.37 minutes
> 

Last part of the console output is:

> i=44 - 105.68 minutes - j=16 - file: 14.tif
> i=44 - 105.68 minutes - j=49 - file: 14.tif
> i=44 - 105.69 minutes - j=1 - file: 14.tif
> i=44 - 105.70 minutes - j=36 - file: 14.tif
> i=44 - 105.70 minutes - j=28 - file: 14.tif
> i=44 - 105.69 minutes - j=37 - file: 14.tif
> i=44 - 105.69 minutes - j=11 - file: 14.tif
> i=44 - 105.71 minutes - j=63 - file: 14.tif
> i=44 - 105.71 minutes - j=38 - file: 14.tif
> i=44 - 105.70 minutes - j=41 - file: 14.tif
> i=44 - 105.70 minutes - j=10 - file: 14.tif
> i=44 - 105.71 minutes - j=27 - file: 14.tif
> i=44 - 105.70 minutes - j=40 - file: 14.tif
> i=44 - 105.70 minutes - j=54 - file: 14.tif
> i=44 - 105.70 minutes - j=59 - file: 14.tif
> i=44 - 105.70 minutes - j=39 - file: 14.tif
> i=44 - 105.70 minutes - j=23 - file: 14.tif
> i=44 - 105.70 minutes - j=29 - file: 14.tif
> i=44 - 105.70 minutes - j=57 - file: 14.tif
> i=44 - 105.71 minutes - j=64 - file: 14.tif
> i=44 - 105.71 minutes - j=15 - file: 14.tif
> i=44 - 105.71 minutes - j=13 - file: 14.tif
> i=44 - 105.71 minutes - j=73 - file: 14.tif
> i=44 - 105.71 minutes - j=31 - file: 14.tif
> i=44 - 105.72 minutes - j=62 - file: 14.tif
> 

I tried to attached it with Visual Studio and very surprising for me that, only one thread remains and could not able to see which line it is locked. I'm not an expert on console applications. If there is no console line limit of 5983 then the application is locked. I checked the system evets and confirmed that windows did not sleep. 

Maybe this would give you a clue: While checking the output file I realised that there are lots of magick files stored in the %temp% directory (number of files that have "magic" prefix is 821; which are 256 GB of size in total) I know about MagickAnyCPU.CacheDirectory use it in the application; but did not use it in this console test.

Have a nice day..

**Comment by korhun** [comment] 2017-10-30 06:47
@dlemstra I got the permission to send you the data as private mail. I could not find your mail address, mine is korhun@gmail.com you may contact me if you need the tiff's I've used for these tests. Regards..

**Comment by dlemstra** [comment] 2017-10-31 18:45
After leaving it running for a whole day I am still not in a deadlock situation:

```
*******ITERATION 156 FINISHED - iteration time: 4.66 minutes - total time: 690.05 minutes
```

But I ran your program with a debugger attached and it looks like the internal book keeping of how much memory is allocated is incorrect. Some memory is released but the book keeping is not updated. And that is why your process is at some point using the disc. But that should only decrease the performance big time but not lock the process. I have no idea why this is happening but I will look into it.

**Comment by korhun** [comment] 2017-11-01 12:55
My and my friends previous tests were all on a normal disc, not SSD. As there is a huge performance difference between memory and a non SSD disk, maybe thats why we thought there was a deadlock. However my last test was something else. It was on a SSD but it was locked on the 43th iteration. And when I attached to it there was only a single thread running and could not see where it was locked; which I expect more than 16 threads. Maybe thats because of something else. I will try to make some other tests when I find time soon. Thank you very much for your effors for this issue.

**Comment by dlemstra** [comment] 2017-11-01 14:42
I left it running on my machine at home and I hope I have more information when I get back home. I added an extra check to log the internal book keeping to be 100% sure that this is causing the issue. It is possible that I made this conclusion to quickly, just want to be sure now. Figuring out what is going on is a slow process so please be patient with me 👍

**Comment by korhun** [comment] 2017-11-02 06:22
Hi, 
We are using Magick.NET-Q8-AnyCPU 7.0.3.0 without any problems. So we are not in a hurry. I make tests not to put you in a pressure but just give a little bit of help on this great library. 
I made a test on another computer. It is Windows 10, 64 bit, 16GB RAM, Xeon 3.50Ghz CPU with a non SSD disk. I use this pc for some machine learning training processes all the time, so I am sure that no sleep has occured. I started the same console exe 12 hours ago and the last outputs are:

> *******ITERATION 108 FINISHED - iteration time: 2,28 minutes - total time: 254,29 minutes
> ...
> i=109 - 256,58 minutes - j=63 - file: 14.tif
> i=109 - 256,58 minutes - j=36 - file: 14.tif
> 

It seems, no console output has been printed for more than 6 hours and it is now using %10 CPU with 18.6MB memory. No CacheDirectory was specified, and on the %temp% directory, there are 76 files that have 'magick' prefix and are 12.9GB in total.

**Comment by dlemstra** [comment] 2017-11-02 18:41
Seem I finally hit the race condition again:

```
*******ITERATION 149 FINISHED - total time: 661.28 minutes - limit: 0
*******ITERATION 150 FINISHED - total time: 665.77 minutes - limit: 0
*******ITERATION 151 FINISHED - total time: 670.11 minutes - limit: 216481792
```

The limit should be zero but is for some odd reason 216481792. Will need to investigate why this is happening. This is very close to max int so that will hopefully give me some pointers.

**Comment by dlemstra** [comment] 2017-11-02 19:36
I do suspect your issues is something else though, but it might be related to what I am seeing. Would it be possible to create a memory dump so I can diagnose the problem better?

**Comment by korhun** [comment] 2017-11-03 12:55
I haven't create a memory dump before. Is it %SystemRoot%\MEMORY.DMP file that you want? (http://mywindowshub.com/how-to-configure-windows-10-to-create-dump-files-on-bsod/) Should I use "Complete Memory Dump" or "Small Memory Dump" and can you give me some info on on how I could create that :)

**Comment by dlemstra** [comment] 2017-11-03 13:38
I would like a dump like this: https://msdn.microsoft.com/en-us/library/d5zhxt22.aspx#Anchor_4

**Comment by dlemstra** [comment] 2017-11-06 19:20
I left your program running for another day. Still not hanging:

```
*******ITERATION 579 FINISHED - iteration time: 1.33 minutes - total time: 765.92 minutes
```

**Comment by korhun** [comment] 2017-11-09 07:57
I am very sorry that I could not send you an dump file yet. It's been very busy here, and I had some urgent issues to be solved. But I will make a test soon..

**Comment by dlemstra** [comment] 2018-01-05 17:44
@korhun Any news on this or can we close this issue?

**Comment by korhun** [comment] 2018-01-08 13:47
@dlemstra I think its better to close this issue. I am sorry that its impossible for me to test this issue with new releases in for a while (not in my control). Currently we are using Magick.NET-Q8-AnyCPU 7.0.3 and nothing negative has ever reported to me so far; however when I find a suitable time, I hope, I'll be able to make tests with your newest releases. I would report as a new issue if I could find anything.

Thank you very much for your efforts.

**Closed** 2018-01-08 14:00 UTC
