### ISSUE TITLE
Crashed when opening some HEIC files

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#533] opened 2019-11-06 15:12 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
- MagickViewer crashed and quit unexpectedly without errors

![image](https://user-images.githubusercontent.com/3154213/68310317-c2df9000-00ea-11ea-8267-ca8949d29986.png)

### Steps to Reproduce
- Drag and drop the HEIC files from https://drive.google.com/open?id=1eqKJG5OZfpbqzDtARZEFRBv-wdMsUfjD to MagickViewer.exe

### System Configuration
- Windows 10 Insider build 18990
- Magick.NET 7.14.5.0

**Comment by dlemstra** [comment] 2019-11-08 11:47
I can reproduce your issue but it looks like something inside the libheif library. I don't have time to look at this for a while but I will try to upgrade libheif in ImageMagick to test if that fixes the issue.

**Comment by fire-eggs** [comment] 2019-11-14 17:46
Not a show-stopper. Thanks again for your continued support!

**Comment by dlemstra** [comment] 2019-11-19 17:38
Updating libheif to vewrsion 1.6.0 did not seem to resolve the problem. Will need to do some more investigating.

**Comment by fire-eggs** [comment] 2019-11-19 19:37
I don't know if it is relevant, but the original submitter claimed the images could be viewed using Windows Photo, after having installed the "heif image extensions from microsoft store".

**Comment by dlemstra** [comment] 2019-11-22 23:51
Reported this upstream. Will now need to wait for an answer.

**Comment by dlemstra** [comment] 2020-01-02 09:48
This issue should be resolved in the latest release (`7.15.0.0`).

**Comment by d2phap** [comment] 2020-01-02 09:48
Thanks a lot!

**Closed** 2020-01-02 09:48 UTC
Labels: bug
