### ISSUE TITLE
AccessViolationException when cloning MagickImage created from corrupt TIFF

### ISSUE THREAD

**Issue by reima** [dlemstra/Magick.NET#1140] opened 2022-02-18 17:03 UTC
### Description
Trying to `Clone` a `MagickImage` instance that has been created by loading the attached [corrupt.tif](https://github.com/dlemstra/Magick.NET/files/8098939/corrupt.tif.zip) file results in an `AccessViolationException`:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_Clone(IntPtr, IntPtr ByRef)
--------------------------------
   at ImageMagick.MagickImage+NativeMagickImage.Clone()
   at ImageMagick.MagickImage..ctor(ImageMagick.IMagickImage`1<Byte>)
   at ImageMagick.MagickImage.Clone()
   at Magick.NET.Samples.Program.Main()
```

### Steps to Reproduce
Compile and run the following .NET 5 application:

```csharp
using ImageMagick;

namespace Magick.NET.Samples
{
    class Program
    {
        static void Main()
        {
            using (var image = new MagickImage("corrupt.tif"))
            {
                image.Clone();
            }
        }
    }
}
```

### System Configuration
- Magick.NET version: Magick.NET-Q8-x64 9.1.2 (and current master branch)
- Environment (Operating system, version and so on): Windows 10

#### Magick++ behavior
The roughly equivalent Magick++ version of the repro program raises an exception when reading the image:

```cpp
#include <Magick++.h>
#include <iostream>

using namespace std;
using namespace Magick;

int main(int argc, char **argv)
{
    InitializeMagick(*argv);

    try
    {
        Image image;
        image.read("corrupt.tif");

        Image clone(image);
    }
    catch (Exception& error)
    {
        cout << "Error: " << error.what() << endl;
    }
}
```

Output:
```
Error: Repro.exe: No image was loaded.
```

#### MagickCore behavior
The MagickCore `ReadImage` function returns `NULL` for this file, but sets no `ExceptionInfo`. I'm not sure if that is something that is allowed to happen, but it does for this file.

**Comment by dlemstra** [comment] 2022-02-18 19:15
Thanks for reporting this. I can also reproduce this issue without the image. The `Clone` method seems to be missing a null check. This will be fixed in the next release.

**Comment by reima** [comment] 2022-02-18 19:31
Great find, didn't think it could be reduced even further.

What are your thoughts on the behavior of `new MagickImage` with the corrupt TIFF? I would have expected an exception in that case, similar to how Magick++ behaves.

**Comment by dlemstra** [comment] 2022-02-18 19:34
This is something inside the TIFF coder. I will need to check inside ImageMagick why this happens and it this can/should be changed.

**Comment by reima** [comment] 2022-02-18 19:41
Thank you so much.

As far as I can tell this is the line where `ReadTIFFImage` returns `NULL` without setting any exception info:

https://github.com/ImageMagick/ImageMagick/blob/ee54f8dcf76a6c82b741cfdf8e0a7b4558671c9d/coders/tiff.c#L1292

If it helps I can create an issue over at ImageMagick for this.

**Comment by dlemstra** [comment] 2022-02-18 19:47
This is something that should be fixed in the `libtiff` library. Some code paths report an error but this path doesn't report an error.

**Comment by dlemstra** [comment] 2022-02-19 06:51
Decided that we will always raise an exception in ImageMagick when none was raised by the tiff library.

**Closed** 2022-02-21 19:49 UTC
