### ISSUE TITLE
System.AccessViolationException using Density with Calibri font

### ISSUE THREAD

**Issue by OvenBaker** [dlemstra/Magick.NET#338] opened 2018-10-17 16:22 UTC
Hi there!

I'm encountering an issue trying to composite text over an image. I'm using the label: and caption: options to "read" in an image. This works without issue until I attempt to set the Density as well; at which point the new MagickImage constructor immediately begins to throw the exception. The code snippet below reliably reproduces the crash. Whilst investigating to file this report; I realised that this issue was specific to the Calibri font. Using Arial or Times New Roman did not cause the fault. I tried setting the font weights and styles; but they did not resolve it. I've provided a minimal replication case below:

```
var textReadSettings = new MagickReadSettings()
{
	FontPointsize = 14,
	FontFamily = "Calibri",
	StrokeColor = MagickColors.Black,
	BackgroundColor = MagickColors.White,
	Height = 180,
	Width = 300,
	Density = new Density(96, 96, DensityUnit.PixelsPerInch),                    
};

using (var textImage = new MagickImage($"label:Masai Mara", textReadSettings))
{
	textImage.Format = MagickFormat.Png;

	var bytes = textImage.ToByteArray();
}
```

### System Configuration
ASP.NET MVC running in a Debug configuration.

- Magick.NET version: Magick.NET-Q16-AnyCPU v.7.9.0.0
- Environment (Operating system, version and so on): Windows 10 x64
- Calibri font information from OS Font Settings:
-- Font file: C:\WINDOWS\FONTS\CALIBRI.TTF
-- Version: 6.22

**Comment by dlemstra** [comment] 2018-10-17 22:30
Thanks for the detailed information and sample. I can reproduce your issue and it looks like we get an exception inside the freetype library. I am not sure yet if this is an ImageMagick issue or a bug in the freetype library. Will need to investigate this.

**Comment by dlemstra** [comment] 2018-10-20 12:33
This bug has been fixed in ImageMagick and will be resolved in the next release.

**Comment by dlemstra** [comment] 2018-10-29 20:29
Just publish Magick.NET 7.9.0.1 that should resolve this issue.

**Closed** 2018-11-10 15:00 UTC
Labels: bug, upstream
