### ISSUE TITLE
How do I get started using Magick.net with .net core?  Where are System.Drawing?

### ISSUE THREAD

**Issue by nikhilsinha** [dlemstra/Magick.NET#77] opened 2017-07-24 02:40 UTC
Hello,

I am attempting to read pixel data out of a png file in a .net core project.  I added Magick.net from nuget.

When I write some code to initialize a MagicImage with a MemoryStream, it says Stream and Object are not defined, and need assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.  It also can't find Bitmap from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.  I don't get these errors when I use .NET Framework.  How do I add these in .net core?

Thank you for your help.

**Comment by meysamSamanpour** [comment] 2017-07-24 16:42
for the memory stream could you please provide us with some code that we can see how you implemented because I have no problem in that area.

for system.drawing I have to say that in .netcore you dont have system.drawing you have to use nuget packages to get similar classes. probably after you add that nuget to your project you need some changes although small changes. 

https://www.nuget.org/packages/CoreCompat.System.Drawing/

**Comment by dlemstra** [comment] 2017-07-24 17:53
You don't need System.Drawing for the .NET Standard build of Magick.NET. Which platform are you targeting?

**Comment by nikhilsinha** [comment] 2017-07-24 18:48
@dlemstra I'm using Magick.NET-Q16-HDRI-AnyCPU.  Is that the wrong one?  I pulled it off NuGet.  The target framework of my webapp is .NETCoreApp 1.1

@meysamSamanpour For those who finds this in the future, make sure you click "Include prerelease" in Visual Studio's nuget package manager.  Otherwise, it won't show up.  Regardless, it still can't find Bitmap. :(

**Comment by dlemstra** [comment] 2017-07-24 21:05
I just created a simple project in VS2017 that use Magick.NET with the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-HDRI-AnyCPU" Version="7.0.6.102" />
  </ItemGroup>

</Project>
```

And that would build without any issues. Can you share a simple project where I can reproduce your issue?

**Comment by nikhilsinha** [comment] 2017-07-25 00:24
I created a clean website, and added references.  I no longer get those errors.  I don't know what's up with my current project.

**Comment by dlemstra** [comment] 2017-07-25 06:08
Do you still need help with your current project or can we close this issue?

**Closed** 2017-08-03 19:05 UTC
Labels: question
