### ISSUE TITLE
Magick.Net returns wrong pixel colors for white image

### ISSUE THREAD

**Issue by Christoph-Wagner** [dlemstra/Magick.NET#403] opened 2019-03-14 13:30 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
using pixel.ToColor() on a white pixel returns 254 (Q8) or 65278 (Q16) instead of 255/65535 for R, G and B. 

Using ImageMagick directly returns the correct values: 
`0,0: (65535,65535,65535)  #FFFFFF  white`

### Steps to Reproduce
Save the attached white.jpg (or create one yourself) and change the path to it in this code. Run it.
```c#
using System;
using System.IO;
using ImageMagick;

namespace CommandRunner
{
    public class MinimalTest
    {
        public static void Main(string[] args)
        {
            var test = new MinimalTest();
            var img = File.ReadAllBytes(@"G:\white.jpg");
            Console.WriteLine(test.GetColor(img));
        }
        private int GetColor(byte[] imageArr)
        {
            using (var image = new MagickImage(imageArr))
            {
                using (var pixels = image.GetPixels())
                {
                    var color = pixels.GetPixel(0, 0).ToColor();
                    if (color.R != color.G || color.G != color.B)
                        throw new Exception();
                    return color.R;
                }
            }
        }
    }
}
```

[white.jpg](https://user-images.githubusercontent.com/1609329/54360458-cce4e800-465c-11e9-8907-bb2e42ac0898.jpg)

### System Configuration

- Magick.NET version: Q16-AnyCPU 7.11.0 (tested with Q8 and x64 as well)
- Environment (Operating system, version and so on): Windows 10 64bit
- Additional information: dotnetcore 2.2

**Comment by dlemstra** [comment] 2019-03-14 14:50
Which version of ImageMagick did you use? It is possible that a bug was fixed recently. Do you also an get incorrect value when you use 7.0.8-28 on the command line? The beta of that version of ImageMagick was used in the latest release.

**Comment by Christoph-Wagner** [comment] 2019-03-14 16:04
It was an older version, around October 2018, I was stupid and just overwrote it to test it with the newest version, 7.0.8-33 (which gives the correct results as well). I don't know where to find old builds of imagemagick, otherwise I'd test -28 as well.

The command I'm using is `magick convert G:\white.jpg out.txt` if you want to see it yourself.

**Comment by dlemstra** [comment] 2019-03-14 16:23
On a phone right now will travel back next week and can test it on a pc then. You might be able to find an older release in the appveyor builds.

**Comment by dlemstra** [comment] 2019-03-23 08:50
I can confirm that this was caused by a bug inside ImageMagick and that this has been resolved with the latest release. The next release of Magick.NET will include a fix for this.

**Closed** 2019-03-24 18:09 UTC
Labels: bug, upstream
