### ISSUE TITLE
`MagickImage.GetColorProfile()` returns non-null value for GIF without color profile

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#1625] opened 2024-05-07 13:48 UTC
### Magick.NET version

13.7.0

### Environment (Operating system, version and so on)

Win 11 23h2

### Description

- The `MagickImage.GetColorProfile()` return non-null for GIF file without color profile.
- Accessing child properties causes `System.NotSupportException` error
- Note that, in v13.6, the `imgM.GetColorProfile()` returns `null` which is correct.

The issue is reported at: https://github.com/d2phap/ImageGlass/issues/1907

### Steps to Reproduce

1. Download sample file:
  ![test.gif](https://github.com/dlemstra/Magick.NET/assets/3154213/9687c7fe-f9de-4f60-9b2c-6d381dd6b307)
2. Run this code with Magick.NET 13.7:
```cs
var path = @"C:\Users\d2pha\Desktop\test.gif";
using var imgM = new MagickImage(path);
var cp = imgM.GetColorProfile();

if (cp != null) // cp is not null here
{
    // accessing cp.ColorSpace throws exception
    var colorSpaceName = cp.ColorSpace.ToString();
}
```
3. See error:
![image](https://github.com/dlemstra/Magick.NET/assets/3154213/e10ba814-7291-4c88-83ad-806f03216fef)

**Comment by dlemstra** [comment] 2024-05-07 17:43
This is caused by the following bug inside ImageMagick: https://github.com/ImageMagick/ImageMagick/issues/7281. This will be resolved in the next release.

**Closed** 2024-05-10 10:59 UTC
